apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30040
  selector:
    app: mongo-standalone-ceph
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo-standalone-ceph
spec:
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-standalone-ceph
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: "/data/db"
              name: cephfs
      volumes:
        - name: cephfs
          cephfs:
            monitors:
            - 10.80.0.1:6789
            - 10.80.0.2:6789
            - 10.80.0.3:6789
            user: admin
            path: /mongo
            secretRef:
              name: ceph-secret
            readOnly: false
