----------------------------------------------
--    新增表：LN_MD_BG_CREDIT_RESULT_ADJ    --
----------------------------------------------
create table IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ(
BUSI_GROUP_NO VARCHAR2(32) not null
,BUSI_GROUP_NAME VARCHAR2(90) not null
,CORE_ENT_NAME VARCHAR2(90) not null
,BUSI_GROUP_NO_S VARCHAR2(32) not null
,TOTAL_LIMIT_S NUMBER(20,2) not null
,TOTAL_LIMIT_ADJ_S NUMBER(20,2)
,IS_FREEZE_S CHAR(1)
,BUSI_GROUP_NO_D VARCHAR2(32) not null
,TOTAL_LIMIT_D NUMBER(20,2) not null
,TOTAL_LIMIT_ADJ_D NUMBER(20,2)
,IS_FREEZE_D CHAR(1)
,EFFECTIVE_FROM_DATE VARCHAR2(8) not null
,EFFECTIVE_TO_DATE VARCHAR2(8) not null
,LIMIT_DATE DATE
,LIMIT_OPRID VARCHAR2(32)
,LIMIT_OPRNAME VARCHAR2(90)
,ADJ_DATE DATE
,ADJ_OPRID VARCHAR2(32)
,ADJ_OPRNAME VARCHAR2(90)
,FREEZE_DATE DATE
,FREEZE_OPRID VARCHAR2(32)
,FREEZE_OPRNAME VARCHAR2(90)
,STATE CHAR(1)
);
alter table IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ add primary key(BUSI_GROUP_NO);
comment on table IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ is '商圈授信调整结果表';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.BUSI_GROUP_NO is '商圈编码';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.BUSI_GROUP_NAME is '商圈名称';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.CORE_ENT_NAME is '核心企业名称';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.BUSI_GROUP_NO_S is '上游额度编码';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.TOTAL_LIMIT_S is '上游供应商总授信额度';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.TOTAL_LIMIT_ADJ_S is '上游供应商总授信额度调整值';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.IS_FREEZE_S is '上游是否冻结';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.BUSI_GROUP_NO_D is '下游额度编码';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.TOTAL_LIMIT_D is '下游经销商总授信额度';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.TOTAL_LIMIT_ADJ_D is '下游经销商总授信额度调整值';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.IS_FREEZE_D is '下游是否冻结';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.EFFECTIVE_FROM_DATE is '生效日期';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.EFFECTIVE_TO_DATE is '到期日期';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.LIMIT_DATE is '授信计算日期';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.LIMIT_OPRID is '授信计算操作员代码';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.LIMIT_OPRNAME is '授信计算操作员名称';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.ADJ_DATE is '授信调整操作日期';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.ADJ_OPRID is '授信调整操作员代码';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.ADJ_OPRNAME is '授信调整操作员名称';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.FREEZE_DATE is '冻结操作日期';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.FREEZE_OPRID is '冻结操作员代码';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.FREEZE_OPRNAME is '冻结操作员名称';
comment on column IBANKWEBUSR.LN_MD_BG_CREDIT_RESULT_ADJ.STATE is '状态';
----------------------------------------------
--      修改表（LN_MID_C3_EUPAYEEINFO）     --
----------------------------------------------
drop table IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO;
create table IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO(
VCHNO VARCHAR2(16)
,ORDERNO NUMBER(6) not null
,PAYEENAME VARCHAR2(105)
,PAYEEACCNO VARCHAR2(30)
,OPENINGBANK VARCHAR2(90)
,PAYMENT NUMBER(18,2)
,PAYTIME VARCHAR2(8)
,BACKUP1 VARCHAR2(90)
,BACKUP2 VARCHAR2(90)
,BACKUP3 NUMBER(18,2)
,OPRINSTCODE VARCHAR2(12)
,OPRID VARCHAR2(20)
,ACCDATE VARCHAR2(8)
,ACCTIME VARCHAR2(6)
,OPDATE VARCHAR2(8)
,OPTIME VARCHAR2(6)
,LOAN_APPLY_NO VARCHAR2(32) not null
);
alter table IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO add primary key(ORDERNO,LOAN_APPLY_NO);
comment on table IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO is 'C3法人贷款凭证收款人信息表';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.VCHNO is '凭证编号';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.ORDERNO is '顺序号';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.PAYEENAME is '收款人名称';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.PAYEEACCNO is '收款人账号';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.OPENINGBANK is '收款人开户行名称';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.PAYMENT is '付款金额';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.PAYTIME is '付款时间';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.BACKUP1 is '备用1';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.BACKUP2 is '备用2';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.BACKUP3 is '备用3';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.OPRINSTCODE is '操作机构编码';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.OPRID is '操作员代码';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.ACCDATE is '首次操作日期';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.ACCTIME is '首次操作时间';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.OPDATE is '操作日期';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.OPTIME is '操作时间';
comment on column IBANKWEBUSR.LN_MID_C3_EUPAYEEINFO.LOAN_APPLY_NO is '贷款编号';
----------------------------------------------
--      修改表（LN_MID_C3_EUREPAYPLAN）     --
----------------------------------------------
drop table IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN;
create table IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN(
VCHNO VARCHAR2(16) not null
,PLANNO NUMBER(6) not null
,CLICODE VARCHAR2(16)
,CURRKIND VARCHAR2(2)
,INTSUM NUMBER(18,2)
,PRIN NUMBER(18,2)
,NOPAYINT NUMBER(18,2)
,PENINT NUMBER(18,2)
,DISOBEYSUM NUMBER(18,2)
,LOANREST NUMBER(18,2)
,BEGINDATE VARCHAR2(8)
,LOANTERM NUMBER(6)
,ENDDATE VARCHAR2(8)
,REPAYWAY VARCHAR2(2)
,BASERATE NUMBER(8,5)
,EXPRATE NUMBER(8,5)
,PECULATERATE NUMBER(8,5)
,FLOATRATE NUMBER(8,5)
,EXECRATE NUMBER(8,5)
,PERREPAYDAY VARCHAR2(2)
,FIRSTREPAYDATE VARCHAR2(8)
,DIVREPAYFLAG VARCHAR2(2)
,EXECDATE VARCHAR2(8)
,APPVNAME VARCHAR2(26)
,PLANSTA CHAR(1)
,ADJCYCLE NUMBER(6)
,ADJSUM NUMBER(18,2)
,ADJRATE NUMBER(18,2)
,DISOBEYRATE NUMBER(18,2)
,CLICODEDEPACC VARCHAR2(20)
,TOTISSUENUM NUMBER(6)
,EXECISSUENUM NUMBER(6)
,REMARK VARCHAR2(250)
,ACCINST VARCHAR2(12)
,OPRINST VARCHAR2(12)
,OPRID VARCHAR2(20)
,OPDATE VARCHAR2(8)
,OPTIME VARCHAR2(6)
);
alter table IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN add primary key(VCHNO,PLANNO);
comment on table IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN is '凭证还款计划';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.VCHNO is '借款凭证编号';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.PLANNO is '还款计划编号';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.CLICODE is '借款人代码';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.CURRKIND is '币种';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.INTSUM is '计息金额';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.PRIN is '其中：本金';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.NOPAYINT is '其中：应付未付利息';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.PENINT is '其中：加罚息';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.DISOBEYSUM is '其中：违约金';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.LOANREST is '贷款余额';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.BEGINDATE is '起始日期';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.LOANTERM is '借款期限';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.ENDDATE is '终止日期';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.REPAYWAY is '还款方式';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.BASERATE is '基准利率(年)';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.EXPRATE is '逾期利率(日)';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.PECULATERATE is '违约利率(日)';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.FLOATRATE is '利率浮动幅度';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.EXECRATE is '执行利率(年)';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.PERREPAYDAY is '每期还款日';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.FIRSTREPAYDATE is '首期还款日期';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.DIVREPAYFLAG is '分期还款周期标志';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.EXECDATE is '还款计划执行日期';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.APPVNAME is '批准人';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.PLANSTA is '还款计划状态';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.ADJCYCLE is '还款调整周期';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.ADJSUM is '调整金额';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.ADJRATE is '调整比率';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.DISOBEYRATE is '违约金比率';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.CLICODEDEPACC is '存款帐号';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.TOTISSUENUM is '计划还款总期数';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.EXECISSUENUM is '已执行还款期数 ';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.REMARK is '备注';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.ACCINST is '放款机构编码';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.OPRINST is '操作机构编码';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.OPRID is '操作员代码';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.OPDATE is '操作日期';
comment on column IBANKWEBUSR.LN_MID_C3_EUREPAYPLAN.OPTIME is '操作时间';
