kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccount: nfs-client-provisioner
      restartPolicy: Always
      containers:
        - name: redis-nfs-client-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/szss_quay_io/nfs-client-provisioner:v2.0.1
          imagePullPolicy: Always
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nas.aliyun.com/nfs
            - name: NFS_SERVER
              value: xxxx.cn-hangzhou.nas.aliyuncs.com
            - name: NFS_PATH
              value: /
      volumes:
        - name: nfs-client-root
          nfs:
            server: xxxx.cn-hangzhou.nas.aliyuncs.com
            path: /
