INSERT INTO "WI_PRODUCT_PRIC" ("PRODUCT_ID", "FORMAT_ID", "QUANTITY", "PRICE", "DISCOUNT_QUANTITY", "DISCOUNT_PRICE", "POINT_RATIO", "OPP_SKU_CODE", "FORMAT_DESC", "FORMAT_NAME") VALUES ('300000000001', '5010', NULL, 1000, NULL, NULL, NULL, 'C026', '保险理财产品（一年后退出不扣费）,预期年化收益率5.5%', '一年期款');
commit;
