--创建商户余额预警表
CREATE TABLE IBANKWEBUSR.WI_RISK_PROVIDER  (
  PROVIDER_ID         CHAR(6),
  MOBILE              VARCHAR2(200),
  EMAIL               VARCHAR2(100),
  RISK_AMT            NUMERIC(20,2),
  RISK_PERCENT        NUMERIC(20,2),
  RISK_MODE           CHAR(1),
  LAST_MSG_TIME       CHAR(17),
  RISK_FLAG           CHAR(1),
  REPEAT_RISK_TIME    VARCHAR2(2)
)
;


COMMENT ON TABLE IBANKWEBUSR.WI_RISK_PROVIDER IS '商户预警信息表';
COMMENT ON COLUMN IBANKWEBUSR.WI_RISK_PROVIDER.PROVIDER_ID IS '商户号';
COMMENT ON COLUMN IBANKWEBUSR.WI_RISK_PROVIDER.MOBILE IS '手机号码';
COMMENT ON COLUMN IBANKWEBUSR.WI_RISK_PROVIDER.EMAIL IS '邮箱地址';
COMMENT ON COLUMN IBANKWEBUSR.WI_RISK_PROVIDER.RISK_AMT IS '预警金额';
COMMENT ON COLUMN IBANKWEBUSR.WI_RISK_PROVIDER.RISK_PERCENT IS '预警金额百分比';
COMMENT ON COLUMN IBANKWEBUSR.WI_RISK_PROVIDER.RISK_MODE IS '预警方式 0-金额 1-百分比' ;
COMMENT ON COLUMN IBANKWEBUSR.WI_RISK_PROVIDER.LAST_MSG_TIME IS '上次预警时间';
COMMENT ON COLUMN IBANKWEBUSR.WI_RISK_PROVIDER.RISK_FLAG IS '预警标识';
COMMENT ON COLUMN IBANKWEBUSR.WI_RISK_PROVIDER.REPEAT_RISK_TIME IS '重复预警间隔';
commit;
