--20140122去掉OL_ORDER_TRACE主键，新增OL_FILE_INCOMING来记录批量文件信息
ALTER TABLE IBANKWEBUSR.OL_ORDER_TRACE DROP CONSTRAINT PK_OL_ORDER_TRACE;

create table IBANKWEBUSR.OL_FILE_INCOMING  (
   FILE_NAME            VARCHAR2(200)  not null,
   PROCESS_TIME         VARCHAR2(17),
   FILE_STATUS          CHAR(1),
   FAIL_REASON          VARCHAR2(4000),
   constraint PK_OL_FILE_INCOMING primary key (FILE_NAME)
);
comment on table IBANKWEBUSR.OL_FILE_INCOMING is
'网购批量文件信息表';
comment on column IBANKWEBUSR.OL_FILE_INCOMING.FILE_NAME is
'文件名';
comment on column IBANKWEBUSR.OL_FILE_INCOMING.PROCESS_TIME is
'操作时间';
comment on column IBANKWEBUSR.OL_FILE_INCOMING.FILE_STATUS is
'文件状态';
comment on column IBANKWEBUSR.OL_FILE_INCOMING.FAIL_REASON is
'失败原因';