apiVersion: v1
kind: Pod
metadata:
  name: cephfs2
spec:
  containers:
  - name: cephfs-rw
    image: nginx
    volumeMounts:
    - mountPath: "/mnt/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - 10.135.204.131:6789
      - 10.135.204.157:6789
      user: admin
      secretRef:
        name: ceph-secret
      readOnly: false
