--修改操作流水表，扩充ACT_ID、OPERATOR_ID长度。
drop table IBANKWEBUSR.WI_MANAGER_ACT_LIST;

CREATE TABLE IBANKWEBUSR.WI_MANAGER_ACT_LIST (
"ACT_ID" VARCHAR2(32 BYTE) NOT NULL ,
"ACT_TYPE" CHAR(2 BYTE) NULL ,
"OPERATOR_ID" CHAR(32 BYTE) NULL ,
"ACT_TIME" CHAR(17 BYTE) NULL ,
"ACT_DESC" VARCHAR2(300 BYTE) NULL ,
"ADD_INFO" VARCHAR2(150 BYTE) NULL 
);

COMMENT ON TABLE "IBANKWEBUSR"."WI_MANAGER_ACT_LIST" IS '管理员操作流水';
COMMENT ON COLUMN "IBANKWEBUSR"."WI_MANAGER_ACT_LIST"."ACT_ID" IS '操作流水号';
COMMENT ON COLUMN "IBANKWEBUSR"."WI_MANAGER_ACT_LIST"."ACT_TYPE" IS '操作类型';
COMMENT ON COLUMN "IBANKWEBUSR"."WI_MANAGER_ACT_LIST"."OPERATOR_ID" IS '操作员';
COMMENT ON COLUMN "IBANKWEBUSR"."WI_MANAGER_ACT_LIST"."ACT_TIME" IS '操作时间';
COMMENT ON COLUMN "IBANKWEBUSR"."WI_MANAGER_ACT_LIST"."ACT_DESC" IS '操作描述';
COMMENT ON COLUMN "IBANKWEBUSR"."WI_MANAGER_ACT_LIST"."ADD_INFO" IS '附加信息';

ALTER TABLE "IBANKWEBUSR"."WI_MANAGER_ACT_LIST" ADD PRIMARY KEY ("ACT_ID");

COMMIT;