ALTER INDEX IBANKTEST.I_EP_ORDER_TRACE1 REBUILD TABLESPACE IBANKTEST ;
ALTER INDEX IBANKTEST.I_EP_ORDER_TRACE7 REBUILD TABLESPACE IBANKTEST ;
ALTER INDEX IBANKTEST.I_EP_ORDER_TRACE6 REBUILD TABLESPACE IBANKTEST ;
ALTER INDEX IBANKTEST.I_EP_ORDER_TRACE5 REBUILD TABLESPACE IBANKTEST ;
ALTER INDEX IBANKTEST.I_EP_ORDER_TRACE4 REBUILD TABLESPACE IBANKTEST ;
ALTER INDEX IBANKTEST.I_EP_ORDER_TRACE3 REBUILD TABLESPACE IBANKTEST ;
ALTER INDEX IBANKTEST.I_EP_ORDER_TRACE2 REBUILD TABLESPACE IBANKTEST ;
ALTER INDEX IBANKTEST.IDX_EP_ORDER_TRACE4 REBUILD TABLESPACE IBANKTEST ;
