
-- #4016 的回滚脚本

DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0124';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0125';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0126';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0127';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0128';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0129';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0130';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0131';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0132';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0133';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0134';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0135';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0136';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0137';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0138';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0139';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0140';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0141';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0142';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0143';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0144';
DELETE FROM CP_ERROR_INFO_COMP WHERE ERROR_CODE = 'LBPJ0145';

