INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('MSG_CP_008', '短信验证码默认模板', '短信验证码', '<p><span style="line-height: 15.98px;">尊敬的客户，您正在${operation}，验证码${phoneAuthCode}，请于五分钟之内输入，工作人员不会向您索取，请勿泄露。</span></p>', 'CP', 3, 3, '0', '09:30', '11:35', '19:27', '23:00', '1', NULL, '发送短信验证码的默认模板', '1', '04', NULL, NULL);
INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('CREDIT_01', '实时农银豆消息', '您的农银豆增加了', '<p>尊敬的${userName}，您在${dateTime}，增加${creditCount}个农银豆。明细如下：${creditDetail}</p>', 'CP', 1, 3, '0', '08:00', '09:00', '11:18', '12:00', NULL, NULL, '对于实时农银豆，发送消息的模板', '1', '04', NULL, 'CREDIT01');
INSERT INTO "CP_MSG_TEMPLATE" (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('MSG_CP_014', '个人一级实名认证成功信息', '个人一级实名认证结果', '<p>&nbsp;尊敬的${name}</p><p>&nbsp;&nbsp;&nbsp;&nbsp;恭喜您！</p><p>&nbsp;&nbsp;&nbsp;&nbsp;您所提交的个人一级实名认证信息已经通过了系统认证，你现在可以进行放心投、安心理等业务。<span style="font-family: 宋体;"></span></p>', 'CP', 3, 3, '0', null, null, null, null, '1', null, '个人一级实名认证定时处理结束', '1', '04', '1', null);
INSERT INTO "CP_MSG_TEMPLATE" (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('MSG_CP_015', '个人一级实名认证失败信息', '个人一级实名认证结果', '<p>&nbsp;尊敬的${name}：<br/>&nbsp;&nbsp;&nbsp;&nbsp;很抱歉通知您！<br/>&nbsp;&nbsp;&nbsp;&nbsp;您所提交的个人一级实名认证信息没有通过我们的认证处理，请您确认您提交的信息是否正确。</p>', 'CP', 3, 3, '0', null, null, null, null, '1', null, '个人一级实名认证失败', '1', '04', '1', null);

INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('MSG_CP_001', '邮箱激活', '请尽快激活您的邮箱', ' ', 'CP', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '01', NULL, NULL);
UPDATE CP_MSG_TEMPLATE SET MSG_CONTENT ='<p><span style="font-size: 14px;font-family: 微软雅黑, sans-serif">尊敬的${userName}：</span></p><p><span style="font-size: 14px;font-family: 微软雅黑, sans-serif"> &nbsp;</span><span style="font-size: 14px;font-family: 微软雅黑, sans-serif">您于<em><span style="font-family:#39;微软雅黑#39;,#39;sans-serif#39;">${time}</span></em>申请验证邮箱，请点击下面的链接完成操作：</span></p><p><span style="font-size: 14px;font-family: 微软雅黑, sans-serif"> &nbsp; &nbsp;</span><span style="font-family: Arial, sans-serif"><a href="http://${domain}/emailValidate/validate?userNo=${userNo}&validateCode=${validateCode}&backToURL=${backToURL}" target="_blank" textvalue="验证邮箱"><span style="font-size:14px;font-family:#39;微软雅黑#39;,#39;sans-serif#39;;color:#00B050">验证邮箱</span></a></span></p><p><span style="font-size: 14px;font-family: 微软雅黑, sans-serif"> </span></p><p><span style="font-size: 14px;font-family: 微软雅黑, sans-serif"></span><span style="font-size: 14px;font-family: 微软雅黑, sans-serif">如果点击无效，请复制下方网址到浏览器地址栏中打开：</span></p>'
|| '<p><span style="font-size: 14px;font-family: 微软雅黑, sans-serif"> &nbsp;http://${domain}/emailValidate/validate?userNo=${userNo}&amp;validateCode=${validateCode}&amp;backToURL=${backToURL}</span></p><p><span style="font-family: 微软雅黑, sans-serif"></span></p><p style="margin: 5px 0;line-height: 24px"><span style="font-size: 14px;font-family: 微软雅黑, sans-serif"> &nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-size: 14px;font-family: 微软雅黑, sans-serif">此邮件由系统自动发送，请勿回复！</span></p><p><span style="font-size: 14px;font-family: 微软雅黑, sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;为保障您的账号安全，请于24小时内完成操作，若您没有申请过验证邮箱，请忽略此邮件，由此给您带来的不便请谅解。</span></p><hr/><p><img src="http://${domain}/base/file/download/f4499d46edfb4050bb2ecb8569dd7a2d99000001" alt=""/>'
|| '<span style="font-family: 微软雅黑, sans-serif; font-size: 14px;"> &nbsp; &nbsp;</span><br/><span style="font-size: 14px;font-family: 微软雅黑, sans-serif"></span></p><p><span style="font-size: 14px;font-family: 微软雅黑, sans-serif">服务热线：</span><strong><span style="font-size:24px;font-family:#39;微软雅黑#39;,#39;sans-serif#39;;color:#00B050">95599</span></strong><em><span style="font-family:#39;微软雅黑#39;,#39;sans-serif#39;;color:#D8D8D8">（周一至周五9:00-18:00）</span></em></p>'
WHERE TEMPLATE_CODE = 'MSG_CP_001';

INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('MSG_CP_002', '邮箱重新绑定', '请尽快完成邮箱重新绑定', ' ', 'CP', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '邮箱重新绑定时发送的邮件', '1', '04', NULL, NULL);
UPDATE CP_MSG_TEMPLATE SET MSG_CONTENT ='<p><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; font-size: 14px;">尊敬的${userName}：</span></p><p><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; font-size: 14px;"><span style="line-height: 1em;"> &nbsp;您于</span><em style="line-height: 1em;">${time}</em><span style="line-height: 1em;">申请重新绑定邮箱，请点击下面的链接完成操作：</span><br/></span></p><p><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; font-size: 14px;"> &nbsp; &nbsp; </span><a href="http://${domain}/emailValidate/validate?userNo=${userNo}&validateCode=${validateCode}&backToURL=${backToURL}" target="_blank" textvalue="激活新邮箱" style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; text-decoration: underline; color: rgb(0, 176, 80);"><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; color: rgb(0, 176, 80);">激活新邮箱</span></a></p><p><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; line-height: 1em; font-size: 14px;"> </span></p><p style="line-height: 1.5em; white-space: normal;"><span style="font-family: 微软雅黑, '
|| '#39;Microsoft YaHei#39;; line-height: 1em; font-size: 14px;">如果点击无效，请复制下方网址到浏览器中打开：<br/></span></p><p style="line-height: 1.5em; white-space: normal;"><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; line-height: 1em; font-size: 14px;"> &nbsp;http://${domain}/emailValidate/validate?userNo=${userNo}&amp;validateCode=${validateCode}&amp;backToURL=${backToURL}<br/></span></p><p><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; line-height: 1em;"></span><br/></p><p style="line-height: 1.5em; white-space: normal;"><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; font-size: 14px;"><span style="line-height: 1em;">为保障您的账号安全，请于24小时内完成操作，若您没有申请过重新绑定邮箱，请忽略此邮件，由此给您带来的不便请谅解。</span></span></p><p style="line-height: 1.5em; white-space: normal;"><br/></p><p style="line-height: 1.5em; white-space: normal;"><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; line-height: 1em; font-size: 14px;"> &nbsp;此邮件由系统自动发送，请勿回复！</span></p><hr/><p style="line-height: 1.5em; white-space: normal;">'
|| '<span style="line-height: 1em; font-family: 微软雅黑, #39;Microsoft YaHei#39;; font-size: 14px;"> </span><img src="http://${domain}/base/file/download/f4499d46edfb4050bb2ecb8569dd7a2d99000001" alt="" style="line-height: 1em;"/><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; font-size: 14px; line-height: 1em;"> &nbsp; &nbsp;</span><br/><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; line-height: 1em; font-size: 14px;"></span></p><p><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; font-size: 14px;">服务热线：<strong><span style="font-family: 微软雅黑, #39;Microsoft YaHei#39;; font-size: 24px; color: rgb(0, 176, 80);">95599</span></strong><span style="font-size: 16px; color: rgb(216, 216, 216);"><em>（周一至周五9:00-18:00）</em></span></span></p>'
WHERE TEMPLATE_CODE = 'MSG_CP_002';

INSERT INTO CP_MSG_TEMPLATE("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") 
VALUES ('MSG_CP_016', '企业一级实名认证成功信息', '企业一级实名认证成功', '<p>尊敬的${chineseFullName}：<br/>&nbsp;&nbsp;&nbsp;&nbsp;恭喜贵公司！<br/>&nbsp;&nbsp;&nbsp;&nbsp;您所提交的企业一级实名认证信息已经通过了系统认证，您现在可以进行放心投、安心理等业务！</p>', 'CP', 3, 3, '0', NULL, NULL, NULL, NULL, '1', NULL, '企业一级实名认证首次认证通过。', '1', '04', '1', NULL);

INSERT INTO CP_MSG_TEMPLATE(TEMPLATE_CODE,TEMPLATE_NAME,MSG_SUBJECT,MSG_CONTENT,PRODUCT_CODE,SEND_LEVEL,DISP_LEVEL,TIME_FLAG,START_TIME1,END_TIME1,START_TIME2,END_TIME2,WEEKEND_FLAG,HOLIDAY_FLAG,DESCRIPTION,TEMPLATE_STATUS,MSG_TYPE,MSG_CHANNEL,TRANS_CODE) VALUES ('MSG_CP_017', '企业二级实名认证成功消息', '企业二级实名认证成功', '尊敬的${chineseFullName}：<br/><p>&nbsp;&nbsp;&nbsp; 经过工作人员的认证审核，您提交的企业资料符合要求，恭喜您顺利通过企业审核!</p><p>&nbsp;&nbsp;&nbsp;&nbsp;您的企业实名认证等级达到2级！</p>', 'CP', 3, 3, '0', NULL, NULL, NULL, NULL, '1', NULL, NULL, '1', '04', '1', NULL);

INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('APPLYEMAIL', '申请行内邮箱增加农银豆', '申请行内邮箱增加农银豆', '<p>applyEmail</p>', 'CP', 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '04', '5', 'APPLYEMAIL');
﻿INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('EP_VT_MSG', '余额转账', '余额转账向收款方发送短信通知', '<clob>${name}经中国农业银行互联网银行向您尾号${inAcctNo}的省心付账户转入${transAmt}元，请注意查收！</clob>', 'EP', 3, 3, '0', '10:00', '15:00', '18:00', '20:00', NULL, NULL, NULL, '1', '04', NULL, NULL);
INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('TRANS_MSG', '银行卡转账', '银行卡转账向收款方发送短信通知', '<clob>您尾号为${accNo}的${cardType}于${transferDate}收到一笔人民币 ${trnAmt} 元的转账，请注意查收！</clob>', 'EP', 3, 3, '0', '10:00', '15:00', '18:00', '20:00', NULL, NULL, NULL, '1', '03', NULL, NULL);
INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('MSG_EP_100', '余额动账', '省心付账户动账短信通知', '<clob>您尾号${acctNo}的省心付账户于${date}${amt}元，余额为${availBalance}元</clob>', 'EP', 3, 1, '0', '10:00', '15:00', '18:00', '20:00', '1', NULL, '虚拟账户金额变动提醒服务', '1', '04', NULL, NULL);
insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_120', '放款通知（邮件）（借款人）', '放款通知', '<p>尊敬的${userName}：</p><p><span class="Apple-tab-span" style="white-space:pre">	</span>您申请的项目：${projName}，借款金额为人民币${applyAmt}元,已完成融资放款。三方协议如附件，请妥善保管！</p><p>&nbsp; 您的收款计划见电子合同，请关注项目的还款状态。详细信息请查看项目详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '放款通知（邮件）（借款人）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_121', '放款通知（邮件）（投资人）', '放款通知', '<p>尊敬的${userName}：</p><p><span class="Apple-tab-span" style="white-space:pre">	</span>您投资的项目：${projName}，投资金额为人民币${applyAmt}元,已完成融资放款。三方协议如附件，请妥善保管！</p><p>&nbsp; 您的还款计划见电子合同。详细信息请查看项目详情：${hlink}</p><p><br/></p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '放款通知（邮件）（投资人）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_210', '融资申请成功通知消息（站内信）', '融资申请成功通知消息', '<p>尊敬的${userName}：您申请的项目：${projName}，借款金额人民币${applyAmt}元的项目已通过中国农业银行互联网银行审批，项目已进入募集阶段。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '融资申请成功通知消息（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_211', '融资申请失败通知消息（站内信）', '融资申请失败通知消息', '<p>尊敬的${userName}：您申请的项目：${projName}，借款金额人民币${applyAmt}元的项目未通过中国农业银行互联网银行审核。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '融资申请失败通知消息（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_220', '放款通知（借款人）（站内信）', '放款通知', '<p>尊敬的${userName}：您申请的项目：${projName}，借款金额为人民币${applyAmt}元的借款已完成融资放款。请关注账户到账。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '放款通知（借款人）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_221', '放款通知（投资人）（站内信）', '放款通知', '<p>尊敬的${userName}：您投资的项目：${projName}，认购金额为人民币${applyAmt}元，现项目已完成资金募集并放款，恭喜您投资成功。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '放款通知（投资人）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_222', '放款审核失败通知（借款人）（站内信）', '放款审核失败通知', '<p>尊敬的${userName}：您申请的项目：${projName}，借款金额为人民币${applyAmt}元，项目未通过放款审核。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '放款审核失败通知（借款人）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_223', '放款审核失败通知（投资人）（站内信）', '放款审核失败通知（投资人）', '<p>尊敬的${userName}：您投资的项目：${projName}，投资金额为人民币${applyAmt}元，项目未通过放款审核。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '放款审核失败通知（投资人）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_230', '融资客户还款前提醒消息（站内信）', '融资客户还款前提醒消息', '<p>尊敬的${userName}：您的借款项目：${projName}，将在${month}月${day}日应归还借款本息人民币${repayAmt}元，借款余额为人民币${balanceAmt}元。请您按时将应还款项存入中国农业银行互联网银行农银通账户。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '融资客户还款前提醒消息（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_234', '宽限期催款单（站内信）', '宽限期催款单', '<p>尊敬的${userName}：您的借款项目：${projName}，在${month}月${day}日应归还借款本息人民币${amt}元，现在${graceDays}天宽限期内。为不影响您的信用记录，请您尽快登陆农行互联网银行进行还款。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '宽限期催款单（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_235', '逾期催款单（站内信）', '逾期催款单', '<p>尊敬的${userName}：您的借款项目：${projName}，在${month}月${day}日应归还借款本息人民币${amt}元，宽限期${graceDays}天，现已逾期${ovdDays}天。为不影响您的信用记录，请您尽快登陆农行互联网银行进行还款。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '逾期催款单（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_240', '标的清偿坏账催收（站内信）', '坏账催收', '<p>尊敬的${userName}：您的借款项目：${projName}，在${month}月${day}日已列入坏账催收处理阶段。中国农业银行受出借人所托对债务进行追偿，中国农业银行保留向人行征信通报您的债务权力，为不影响您的信用记录，请您尽快登陆农行互联网银行进行还款。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的清偿，坏账催收（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_241', '标的清偿（投资人）（站内信）', '标的清偿消息', '<p>尊敬的${userName}：您的投资项目：${projName}，由于借款人逾期后一直未还，根据本息保障计划，平台已对项目进行清偿。请注意查看项目和资金到账情况。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的清偿（投资人）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_250', '标的满标通知（借款人）（站内信）', '标的满标通知', '<p>尊敬的${userName}：您的借款项目：${projName}，在${month}月${day}日完成资金募集，已进入放款审核流程。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的满标通知（借款人）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_251', '标的满标通知（投资人）（站内信）', '标的满标通知', '<p>尊敬的${userName}：您的投资项目：${projName}，在${month}月${day}日完成资金募集，已进入放款审核流程。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的满标通知（投资人）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_252', '标的流标通知（借款人）（站内信）', '标的流标通知', '<p>尊敬的${userName}：您的借款项目：${projName}，在${month}月${day}日未完成资金募集，标的已经流标。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的流标通知（借款人）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_253', '标的流标通知（投资人）（站内信）', '标的流标通知', '<p>尊敬的${userName}：您的投资项目：${projName}，在${month}月${day}日未完成资金募集，您的认购已经失效。认购款项将返还到您的账户，请关注。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的流标通知（投资人）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_260', '投资客户正常收款消息（站内信）', '投资客户正常收款消息', '<p>尊敬的${userName}：您的投资项目：${projName}，已在${month}月${day}日完成第${period}期收款，收款本息金额为人民币${amt}元。详情：${hlink}</p>', 'LB', 2, 2, '0', '', '', '', '', '1', '', '投资客户正常收款消息（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_261', '标的提前还款投资客户收款消息（站内信）', '标的提前还款投资客户收款消息', '<p>尊敬的${userName}：您的投资项目：${projName}，在${month}月${day}日借款人已经提前还款。您的提前收款本息金额为人民币${amt}元，已收违约金额为人民币${pbc}元。详情：${hlink}</p>', 'LB', 2, 2, '0', '', '', '', '', '1', '', '标的提前还款，投资客户收款消息（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_262', '标的逾期还款投资客户收款消息（站内信）', '标的逾期还款投资客户收款消息', '<p>尊敬的${userName}：您的投资项目：${projName}，在${month}月${day}日借款人完成第${period}期还款。您的收款本息金额为人民币${amt}元，已收罚息金额为人民币${rpi}元。详情：${hlink}</p>', 'LB', 2, 2, '0', '08:00', '22:00', '', '', '1', '', '标的逾期还款，投资客户收款消息（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_265', '借款客户自动还款（足额）（站内信）', '借款客户自动还款', '<p>尊敬的${userName}：您的借款项目：${projName}，已在${month}月${day}日完成第${period}期还款，还款总额为人民币${amt}元，投资人本息${amt1}元，账户管理费${amt2}元。详情：${hlink}</p>', 'LB', 3, 3, '0', '08:00', '22:00', '', '', '1', '', '借款客户自动还款（足额）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_266', '借款客户自动还款（不足额催款）（站内信）', '借款客户不足额催款', '<p>尊敬的${userName}：您的借款项目：${projName}，应在${month}月${day}日完成第${period}期还款，应还款总额为人民币${amt}元，您虚拟账户中${amt1}元已经转入扣款户。为不影响您的信用记录，请您尽快还款。详情：${hlink}</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '借款客户自动还款（不足额催款）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_267', '平台本息保障（赔付）（投资人）（站内信）', '平台本息保障', '<p>尊敬的${userName}：根据平台本息保证计划，现归还您的借款项目：${projName}，第${period}期本息${amt}元。详情：${hlink}</p>', 'LB', 2, 2, '0', '', '', '', '', '1', '', '平台本息保障（赔付）（投资人）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_268', '借款客户自动还款（逾期还款）（站内信）', '借款客户逾期还款', '<p>尊敬的${userName}：您的借款项目：${projName}，已在${month}月${day}日完成第${period}期还款，还款总额为人民币${amt}元，投资人本息${amt1}元，账户管理费${amt2}元，罚息${amt3}元，延期账户管理费${amt4}元。详情：${hlink}</p>', 'LB', 3, 3, '0', '08:00', '22:00', '', '', '1', '', '借款客户自动还款（逾期还款）（站内信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_310', '融资申请成功通知消息（短信）', '融资申请成功通知消息', '<p>尊敬的${userName}：您申请的项目：${projName}，借款金额人民币${applyAmt}元的项目已通过中国农业银行互联网银行审批，项目已进入募集阶段。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '融资申请成功通知消息（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_311', '融资申请失败通知消息（短信）', '融资申请失败通知消息', '<p>尊敬的${userName}：您申请的项目：${projName}，借款金额人民币${applyAmt}元的项目未通过中国农业银行互联网银行审核。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '融资申请失败通知消息（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_320', '放款通知（借款人）（短信）', '放款通知', '<p>尊敬的${userName}：您申请的项目：${projName}，借款金额为人民币${applyAmt}元的借款已完成融资放款。请关注账户到账。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '放款通知（借款人）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_321', '放款通知（投资人）（短信）', '放款通知', '<p>尊敬的${userName}：您投资的项目：${projName}，认购金额为人民币${applyAmt}元，现项目已完成资金募集并放款，恭喜您投资成功。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '放款通知（投资人）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_322', '放款审核失败通知（借款人）（短信）', '放款审核失败通知', '<p>尊敬的${userName}：您申请的项目：${projName}，借款金额为人民币${applyAmt}元，项目未通过放款审核。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '放款审核失败通知（借款人）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_323', '放款审核失败通知（投资人）（短信）', '放款审核失败通知', '<p>尊敬的${userName}：您投资的项目：${projName}，投资金额为人民币${applyAmt}元，项目未通过放款审核。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '放款审核失败通知（投资人）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_330', '融资客户还款前提醒消息（短信）', '还款前提醒消息', '<p>尊敬的${userName}：您的借款项目：${projName}，将在${month}月${day}日应归还借款本息人民币${repayAmt}元，借款余额为人民币${balanceAmt}元。请您按时将应还款项存入中国农业银行互联网银行农银通账户。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '融资客户还款前提醒消息（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_334', '宽限期催款单（短信）', '宽限期催款单', '<p>尊敬的${userName}：您的借款项目：${projName}，在${month}月${day}日应归还借款本息人民币${amt}元，现在${graceDays}天宽限期内。为不影响您的信用记录，请您尽快登陆农行互联网银行进行还款。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '宽限期催款单（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_335', '逾期催款单（短信）', '逾期催款单', '<p>尊敬的${userName}：您的借款项目：${projName}，在${month}月${day}日应归还借款本息人民币${amt}元，宽限期${graceDays}天，现已逾期${ovdDays}天。为不影响您的信用记录，请您尽快登陆农行互联网银行进行还款。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '逾期催款单（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_340', '标的清偿坏账催收（短信）', '坏账催收', '<p>您的借款项目：${projName}，在${month}月${day}日已列入坏账催收处理阶段。中国农业银行受出借人所托对债务进行追偿，中国农业银行保留向人行征信通报您的债务权力，为不影响您的信用记录，请您尽快登陆农行互联网银行进行还款。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的清偿，坏账催收（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_341', '标的清偿（投资人）（短信）', '标的清偿消息', '<p>尊敬的${userName}：您的投资项目：${projName}，由于借款人逾期后一直未还，根据本息保障计划，平台已对项目进行清偿。请注意查看项目和资金到账情况。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的清偿（投资人）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_350', '标的满标通知（借款人）（短信）', '标的满标通知', '<p>尊敬的${userName}：您的借款项目：${projName}，在${month}月${day}日完成资金募集，已进入放款审核流程。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的满标通知（借款人）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_351', '标的满标通知（投资人）（短信）', '标的满标通知', '<p>尊敬的${userName}：您的投资项目：${projName}，在${month}月${day}日完成资金募集，已进入放款审核流程。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的满标通知（投资人）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_352', '标的流标通知（借款人）（短信）', '标的流标通知', '<p>尊敬的${userName}：您的借款项目：${projName}，在${month}月${day}日未完成资金募集，标的已经流标。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的流标通知（借款人）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_353', '标的流标通知（投资人）（短信）', '标的流标通知', '<p>尊敬的${userName}：您的投资项目：${projName}，在${month}月${day}日未完成资金募集，您的认购已经失效。认购款项将返还到您的账户，请关注。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '标的流标通知（投资人）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_360', '投资客户正常收款消息（短信）', '投资客户正常收款消息（短信）', '<p>尊敬的${userName}：您的投资项目：${projName}，已在${month}月${day}日完成第${period}期收款，收款本息金额为人民币${amt}元。</p>', 'LB', 2, 2, '1', '08:00', '22:00', '', '', '1', '', '投资客户正常收款消息（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_361', '标的提前还款投资客户收款消息（短信）', '提前还款收款消息', '<p>尊敬的${userName}：您的投资项目：${projName}，在${month}月${day}日借款人已经提前还款。您的提前收款本息金额为人民币${amt}元，已收违约金额为人民币${pbc}元。</p>', 'LB', 2, 2, '1', '08:00', '22:00', '', '', '1', '', '标的提前还款，投资客户收款消息（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_362', '标的逾期还款投资客户收款消息（短信）', '逾期还款收款消息', '<p>尊敬的${userName}：您的投资项目：${projName}，在${month}月${day}日借款人完成第${period}期还款。您的收款本息金额为人民币${amt}元，已收罚息金额为人民币${rpi}元。</p>', 'LB', 2, 2, '1', '08:00', '22:00', '', '', '1', '', '标的逾期还款，投资客户收款消息（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_365', '借款客户自动还款（足额）（短信）', '借款客户自动还款', '<p>尊敬的${userName}：您的借款项目：${projName}，已在${month}月${day}日完成第${period}期还款，还款总额为人民币${amt}元，投资人本息${amt1}元，账户管理费${amt2}元。</p>', 'LB', 3, 3, '1', '08:00', '22:00', '', '', '1', '', '借款客户自动还款（足额）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_366', '借款客户自动还款（不足额催款）（短信）', '借款客户不足额催款', '<p>尊敬的${userName}：您的借款项目：${projName}，应在${month}月${day}日完成第${period}期还款，应还款总额为人民币${amt}元，您虚拟账户中${amt1}元已经转入扣款户。为不影响您的信用记录，请您尽快还款。</p>', 'LB', 3, 3, '0', '', '', '', '', '1', '', '借款客户自动还款（不足额催款）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_367', '平台本息保障（赔付）（投资人）（短信）', '平台本息保障', '<p>尊敬的${userName}：根据平台本息保证计划，现归还您的借款项目：${projName}，第${period}期本息${amt}元。</p>', 'LB', 2, 2, '1', '08:00', '22:00', '', '', '1', '', '平台本息保障（赔付）（投资人）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_368', '借款客户自动还款（逾期还款）（短信）', '借款客户逾期还款', '<p>尊敬的${userName}：您的借款项目：${projName}，已在${month}月${day}日完成第${period}期还款，还款总额为人民币${amt}元，投资人本息${amt1}元，账户管理费${amt2}元，罚息${amt3}元，延期账户管理费${amt4}元。</p>', 'LB', 3, 3, '1', '08:00', '22:00', '', '', '1', '', '借款客户自动还款（逾期还款）（短信）', '1', '01', '', '');

insert into CP_MSG_TEMPLATE (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE)
values ('MSG_LB_401', '投资邀请（站内信）', '投资邀请', '<p>
    ${content}
</p><p>
    <a style="text-decoration: underline; background-color: rgb(255, 255, 255); color: rgb(0, 176, 80);" href="${inviteAddress}"><span style="background-color: rgb(255, 255, 255); color: rgb(0, 176, 80);"><strong>去看看</strong></span></a>
</p>
', 'LB', 2, 2, '0', '08:00', '22:00', '', '', '', '', '投资人认购成功后或者融资人申请通过后邀请好友投资', '1', '01', '', '');

﻿--删除可能存在的数据
--delete from CP_MSG_TEMPLATE where template_code like 'LN_%';
--commit;

--写入数据
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_APP_FIL', '通知客户经理审核贷款资料', '待审核贷款资料', '<p>${managerName}您好，您的客户${enterName}已经提交贷款资料，请尽快审核！</p>', 'LN', 2, 2, '0', null, null, null, null, '1', null, '企业客户提交贷款信息后，向ERP客户经理发送短信提示尽快审批。', '1', '04', '2', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_CK_AE', '复核通过待提交审批消息模板', '复核通过待提交审批消息', '<p>尊敬的${userName}：您好。贵公司的贷款申请（编号${loanApplyNo}）已经复核通过，请及时登录我行互联网银行系统进行提交审批处理。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '贷款复核通过后需给操作员发送消息。', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_FIL_PST', '贷款资料审核通过通知', '通知', '<p>尊敬的客户，您提交的贷款资料已经审核通过，现在可以登录我行互联网银行系统进行贷款申请。</p>', 'LN', 2, 2, '0', '08:00', '22:00', null, null, '1', null, null, '1', '04', null, null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_AAI1', '自动审批通过消息模板', '自动审批通过发送消息', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）已通过审批，请登录中国农业银行农银通查看详细信息，为避免申请失效，请尽快确认审批结果。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批通过后,发送通过消息', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_AAI2', '自动审批拒绝消息模板', '自动审批拒绝后发送消息', '<p>尊敬的${userName}：您好，抱歉的通知您，您的贷款申请（编号${loanApplyNo}）未能通过审批，请登录中国农业银行农银通查看详细信息。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批拒绝后,发送消息', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_AAI3', '自动审批需人工处理消息模板', '自动审批需人工处理消息', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）需要我行审批人员人工审批，我们将及时反馈审批结果，请您耐心等待。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批状态为需人工处理时,发送消息', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_AAM4', '自动审批需转人工处理消息模板', '自动审批需转人工处理消息', '<p>尊敬的${admmgrName}：您好，客户${entName}的贷款申请（编号${loanApplyNo}）需要提交人工审批，请及时登录我行互联网银行系统进行处理。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '贷款自动审批后需转人工审批时给客户经理发送消息。', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_AARI', '确认审批结果后签订合同消息模板', '确认审批结果后签订合同消息', '<p>尊敬的${userName}：您好，您已确认贷款申请（编号${loanApplyNo}）的审批结果，为避免申请失效，请尽快签订合同。谢谢！</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '确认审批结果后签订合同消息', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_ATME', '自动转人工审批邮件信息模板', '自动转人工审批邮件信息', '<p>尊敬的${userName}：您好，客户${entName}的贷款申请(编号${loanApplyNo})需要你人工审批，请及时登录我行互联网银行系统进行处理。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批转人工审批操作后，给审批人发送邮件。', '1', '04', '3', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_ATMI', '自动转人工审批站内消息模板', '自动审批转人工审批消息', '<p>尊敬的${userName}：您好，客户${entName}的贷款申请(编号${loanApplyNo})需要你人工审批，请及时登录我行互联网银行系统进行处理。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批转人工审批，给审批人发送消息', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_ATMM', '自动转人工审批短信信息模板', '自动转人工审批短信信息', '<p>尊敬的${userName}：您好，客户${entName}的贷款申请(编号${loanApplyNo})需要你人工审批，请及时登录我行互联网银行系统进行处理。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批转人工审批操作后，给审批人发送短信。', '1', '04', '2', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAE1', '人工审批通过时发送邮件模版', '人工审批通过时发送审批通过邮件', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）已通过审批，请登录中国农业银行农银通查询详细信息，为避免申请失效，请尽快确认审批结果。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '人工审批后，给用户发送审批结果，审批通过后提示用户确认审批结果。', '1', '04', '3', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAE2', '人工审批拒绝时发送邮件模版', '人工审批拒绝时发送邮件', '<p>尊敬的${userName}：您好，抱歉的通知您，您的贷款申请（编号${loanApplyNo}）未能通过审批，请登录中国农业银行农银通查看详细信息。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '审批不通过： 人工审批后，给用户发送审批结果，审批不通过，则通知用户审批不通过信息。', '1', '04', '3', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAI1', '人工审批通过时发送消息模版', '人工审批通过时发送审批通过消息', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）已通过审批，请登录中国农业银行农银通查询详细信息，为避免申请失效，请尽快确认审批结果。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '人工审批后，给用户发送审批结果，审批通过后提示用户确认审批结果。', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAI2', '人工审批拒绝时发送消息模版', '人工审批拒绝时发送消息', '<p>尊敬的${userName}：您好，抱歉的通知您，您的贷款申请（编号${loanApplyNo}）未能通过审批，请登录中国农业银行农银通查看详细信息。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '人工审批后，给用户发送审批结果，审批不通过，提示用户审批不通过信息。', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAM1', '人工审批通过时发送短信模版', '人工审批通过时发送短信', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）已通过审批，请登录中国农业银行农银通查看详细信息，为避免申请失效，请尽快确认审批结果。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '人工审批后，给用户发送审批结果，审批通过后提示用户确认审批结果。', '1', '04', '2', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAM2', '人工审批拒绝时发送短信模版', '人工审批拒绝时发送短信', '<p>尊敬的${userName}：您好，抱歉的通知您，您的贷款申请（编号${loanApplyNo}）未能通过审批，请登录中国农业银行农银通查看详细信息。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '人工审批后，给用户发送审批结果，审批不通过，则通知用户审批不通过信息。', '1', '04', '2', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_SGN_CNT', '合同签订消息', '签约合同成功', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）签约合同成功，正进入放款阶段，请登录系统查看详情。</p>', 'LN', 3, 3, '0', '08:00', '10:00', '08:00', '22:00', '1', null, '签约合同成功消息', '1', '04', null, null);
commit;
﻿--OL cp_msg_template
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('SOCIAL_001', '好友分享动态', '好友动态-分享', '<p> 您的好友${friendsName}分享了：${friendsMsgContent}。</p><p> <a style="text-decoration: underline; background-color: rgb(255, 255, 255); color: rgb(0, 176,80);" href="${friendsActivityURL}" target="_blank"><span style="background-color: rgb(255, 255,255); color: rgb(0, 176, 80);"><strong>去看看</strong></span></a></p>', 'OL', 2, 2, '0', '', '', '', '', '1', '', '用户A因分享产生的一条消息，他的好友都会收到来自于A的这条动态消息。【好友动态】', '1', '01', '1', 'SOCIAL_001');
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('SOCIAL_002', '好友评价动态', '好友动态-评价', '<p>您的好友${friendsName}发表了评价：${friendsMsgContent}。</p><p><a style="text-decoration: underline; background-color: rgb(255, 255, 255); color: rgb(0, 176, 80);" href="${friendsActivityURL}" target="_target"><span style="background-color: rgb(255, 255, 255); color: rgb(0, 176, 80);">去看看</span></a></p>', 'OL', 2, 2, '0', '', '', '', '', '1', '', '用户A评价了一条消息，他的好友都能够看到他的评价！', '1', '01', '1', 'SOCIAL_002');

commit;

﻿INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('MSG_WI_101', '理财订单支付成功', '订单支付成功', '<p>尊敬的用户，您购买的保险产品：${productName}，订单号为：${orderno}已支付成功。</p><p></p>', 'WI', 3, 3, '0', '08:00', '11:00', '14:00', '16:00', '1', NULL, '订单支付成功', '1', '01', NULL, NULL);
INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('MSG_WI_102', '理财退保赎回成功', '退保赎回成功', '<p>尊敬的用户，您购买的保险产品：${productName}，订单号为：${orderno}，退保/赎回已成功。</p><p></p>', 'WI', 3, 3, '0', '08:00', '11:00', '14:00', '16:00', '1',  NULL, '退保赎回成功', '1', '01', NULL, NULL);
INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('MSG_WI_103', '理财商户虚拟账户余额过少', '虚拟账户余额即将不足', '<p>${providerName}:请注意，贵公司的虚拟账户余额为${balance}，已经低于警报线，请及时充值，以免造成客户退保/赎回失败。</p><p></p>', 'WI', 3, 3, '0', '08:00', '11:00', '14:00', '16:00', '1', NULL, '虚拟账户余额过少', '1', '01', NULL, NULL);
INSERT INTO "CP_MSG_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE_NAME", "MSG_SUBJECT", "MSG_CONTENT", "PRODUCT_CODE", "SEND_LEVEL", "DISP_LEVEL", "TIME_FLAG", "START_TIME1", "END_TIME1", "START_TIME2", "END_TIME2", "WEEKEND_FLAG", "HOLIDAY_FLAG", "DESCRIPTION", "TEMPLATE_STATUS", "MSG_TYPE", "MSG_CHANNEL", "TRANS_CODE") VALUES ('WIPURCHASE', '投保成功后的增加农银豆服务', '投保成功后增加农银豆', '<p>WIPurchase</p>', 'WI', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '04', '5', 'WIPURCHASE');
commit;
