INSERT INTO "CP_SERIAL_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE", "DESCRIPTION", "CACHED_COUNT", "COUNTER") VALUES ('RecheckNo', '(DATE,yyyyMMddhhmmss)(SERIAL,C6)', '复核记录号', 100, 6600);
INSERT INTO "CP_SERIAL_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE", "DESCRIPTION", "CACHED_COUNT", "COUNTER") VALUES ('busiGroupCode', '00S[year,C2](SERIAL,C5)', '商圈编号:00S+<2位年份>+<5位序号,取序号表>', 1, 2);
INSERT INTO "CP_SERIAL_TEMPLATE" ("TEMPLATE_CODE", "TEMPLATE", "DESCRIPTION", "CACHED_COUNT", "COUNTER") VALUES ('StaffNo', '[ABC,C3](SERIAL,C8)', '管理后台员工编号', 1, 30);

﻿insert into CP_SERIAL_TEMPLATE (TEMPLATE_CODE, TEMPLATE, DESCRIPTION, CACHED_COUNT, COUNTER)
values ('PlatformNo', 'I(DATE,yyyyMMddHHmmss)B(SERIAL,C4)', '支付  平台流水号', 12, 5487);
insert into CP_SERIAL_TEMPLATE (TEMPLATE_CODE, TEMPLATE, DESCRIPTION, CACHED_COUNT, COUNTER)
values ('AcctNoTemplate', '[ID,C5][sort,C1][area,C2](SERIAL,C10)', '虚拟账号的生成规则', 512, 135407);
commit;
insert into CP_SERIAL_TEMPLATE (TEMPLATE_CODE, TEMPLATE, DESCRIPTION, CACHED_COUNT, COUNTER)
values ('P2PprojectId', '(DATE,yyMMddHHmmss)(SERIAL,C5)', '融资申请项目编号', 1, 1604);

﻿
--序号表
insert into CP_SERIAL_TEMPLATE (TEMPLATE_CODE, TEMPLATE, DESCRIPTION, CACHED_COUNT, COUNTER)
values ('BoeingTransationSeqNo', '(DATE,yyyyMMddhhmmss)(SERIAL,C6)', 'boeing交易流水，20位', 100, 1);

insert into CP_SERIAL_TEMPLATE (TEMPLATE_CODE, TEMPLATE, DESCRIPTION, CACHED_COUNT, COUNTER)
values ('BoeingSeqNo', 'EPBOEING(DATE,yyyyMMddhhmmss)(SERIAL,C9)', 'pancloud integration BOEING流水号', 100, 1);

insert into CP_SERIAL_TEMPLATE (TEMPLATE_CODE, TEMPLATE, DESCRIPTION, CACHED_COUNT, COUNTER)
values ('C3AddCustomer', '(DATE,yyyyMMdd)(SERIAL,C5)', 'C3开户流水号', 100, 1);

insert into CP_SERIAL_TEMPLATE (TEMPLATE_CODE, TEMPLATE, DESCRIPTION, CACHED_COUNT, COUNTER)
values ('LoanApplyNo', '[CN,C2][TYPE,C3](DATE,yyyy)(SERIAL,C9)', '贷款申请流水号规则', 100, 1);

insert into CP_SERIAL_TEMPLATE (TEMPLATE_CODE, TEMPLATE, DESCRIPTION, CACHED_COUNT, COUNTER)
values ('LoanProdId', 'LP[PRODID,C2](SERIAL,C9)', '贷款产品编号', 1, 100);
insert into CP_SERIAL_TEMPLATE (TEMPLATE_CODE, TEMPLATE, DESCRIPTION, CACHED_COUNT, COUNTER)
values ('LoanBusiparamId', 'LB[PARID,C2](SERIAL,C9)', '贷款业务参数', 1, 100);
insert into CP_SERIAL_TEMPLATE (TEMPLATE_CODE, TEMPLATE, DESCRIPTION, CACHED_COUNT, COUNTER)
values ('LoanParamId', 'LP[PARAMID,C2](SERIAL,C9)', '定价参数编号', 1, 100);

commit;
INSERT INTO "CP_SERIAL_TEMPLATE" VALUES ('WIProductID', '[CateID,C4](SERIAL,C8)', '理财商品编号', 100, 1);
INSERT INTO "CP_SERIAL_TEMPLATE" VALUES ('WISerialTemp', '[Module,C2][Time,C14](SERIAL,C5)', '理财平台流水号规则', 100, 1);
commit;
