--回滚数据
--写入数据
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMDR019', '您查询商圈的评价等级校验临界值为空', '您查询商圈的评价等级校验临界值为空', null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5001','自动审批结果查询异常！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5002','自动审批结果不存在！','业务数据异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5003','自动审批结果插入失败！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5004','自动审批结果更新失败！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5005','贷款申请信息查询异常！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5006','贷款申请信息不存在！','该贷款申请号无记录。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5007','申请信息已失效！','该笔贷款申请的审批金额已经失效，无法继续办理业务，请您重新发起贷款申请。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5008','贷款申请环节异常！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5009','当前环节不为[{0}]，无法进行该操作！','当前环节不为[{0}]，无法进行该操作！',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5010','贷款申请信息状态更新失败！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5036','审批登记信息不存在','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5037','贷款资料信息不存在！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5038','定价结果不存在！','业务数据异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5039','人工审批时间格式错误！','业务数据异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5040','自动审批时间格式错误！','业务数据异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5041','审批机构不存在！','业务数据异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5042','C3服务地址不存在！','业务数据异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5043','C3返回结果为空！','业务数据异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5044','C3返回XML解析异常！','业务数据异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5045','审批登记信息更新失败！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5046','C3对照关系信息查询失败！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5047','C3对照关系信息更新失败！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5048','C3对照关系信息写入失败！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5049','贷款申请利率信息查询失败！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5050','贷款申请利率信息不存在！','业务数据异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5051','定价结果更新失败','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5052','C3服务未开放或连接超时！','请在8:00-22:00间进行确认审批结果操作，如果您已经在提示时段内进行操作，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5053','C3远程服务异常！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5054','C3URL解析异常！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5055','C3服务对象生成异常！','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5056','审批登记查询异常','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5057','客户贷款信息查询异常','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5058','人工审批结果查询异常','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5059','定价结果查询异常','系统异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5065','C3新增审批登记信息异常，异常代码：[{0}],异常原因：[{1}]','审批数据落地异常，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI5086','贷款申请利率信息数据错误！','贷款申请利率信息有误，请联系您的客户经理。',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9073','借款凭证信息写入失败','借款凭证信息写入失败',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9074','C3新增借款凭证异常，异常代码：[{0}],异常原因：[{1}]','C3新增借款凭证异常，异常代码：[{0}],异常原因：[{1}]',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9075','借款合同状态不为生效，无法新增凭证','借款合同状态不为生效，无法新增凭证',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9076','借款凭证写入失败！','借款凭证写入失败！',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9077','C3新增凭证附加信息异常，异常代码：[{0}],异常原因：[{1}]','C3新增凭证附加信息异常，异常代码：[{0}],异常原因：[{1}]',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9078','C3新增凭证还款计划异常，异常代码：[{0}],异常原因：[{1}]','C3新增凭证还款计划异常，异常代码：[{0}],异常原因：[{1}]',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9079','凭证查询异常','凭证查询异常',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9080','该笔凭证不存在！','该笔凭证不存在！',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9081','凭证利率写入异常！','凭证利率写入异常！',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9082','C3新增凭证利率异常，异常代码：[{0}],异常原因：[{1}]','C3新增凭证利率异常，异常代码：[{0}],异常原因：[{1}]',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9083','合同利率查询异常！','凭证利率更新异常！',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9084','凭证利率更新异常！','凭证利率更新异常！',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9085','C3借款凭证生效异常，异常代码：[{0}],异常原因：[{1}]','C3借款凭证生效异常，异常代码：[{0}],异常原因：[{1}]',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9086','贷款申请利率信息数据错误！','贷款申请利率信息数据错误！',null);
insert into CP_ERROR_INFO_COMP (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI9087','企业征信源信息更新异常','企业征信源信息更新异常',null);
insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNCM7028', '企业编码为空', '企业编码为空', 'ENT_NO_NULL');
insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNCM7029', '获取企业编号为[[{0}]]的账户关联信息异常', '获取企业编号为[[{0}]]的账户关联信息异常', 'GET_ENT_ACCT_MASTER_ERROR');
insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNCM7030', '企业编号为[[{0}]]的账户关联信息不存在', '企业编号为[[{0}]]的账户关联信息不存在', 'ENT_ACCT_MASTER_NONE');
insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNCM7031', '编号为[[{0}]]企业账户的ID为空', '编号为[[{0}]]企业账户的ID为空', 'ENT_ACCT_MASTER_NO_NULL');
insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNCM7032', '获取企业编号为[[{0}]]账户下的企业类型的银行卡列表异常', '获取企业编号为[[{0}]]账户下的企业类型的银行卡列表异常', 'GET_ENT_BANK_CARDS_ERROR');
insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNCM7033', '企业编号为[[{0}]]账户下的企业类型的银行卡不存在', '企业编号为[[{0}]]账户下的企业类型的银行卡不存在', 'ENT_BANK_CARDS_NONE');
insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME)
values ('LNCM7034', '企业编码为[[{0}]]的商圈企业成员信息不存在', '企业编码为[[{0}]]的商圈企业成员信息不存在', 'GET_BUSI_GROUP_MEMBER_BY_ENT_NO_NONE');

insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME)
values ('LNCM7035', '用户ID为空', '用户ID为空', 'USER_ID_NULL');

insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI7046', '贷款申请编号为[[{0}]]还款信息不存在', '贷款申请编号为[[{0}]]还款信息不存在', 'LOAN_CON_INFO_NONE');
insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI7047', '获取贷款申请编号为[[{0}]]还款信息异常', '获取贷款申请编号为[[{0}]]还款信息异常', 'GET_LOAN_CON_INFO_ERROR');
insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI7048', '获取贷款申请编号为[[{0}]]逾期信息异常', '获取贷款申请编号为[[{0}]]逾期信息异常', 'GET_EZAB_INFO_ERROR');
insert into cp_error_info_comp (ERROR_CODE, ERROR_SYS_DESC, ERROR_USER_DESC, ERROR_NAME) values ('LNMI7049', '贷款申请编号为[[{0}]]逾期信息不存在', '贷款申请编号为[[{0}]]逾期信息不存在', 'LN_EZAB_INFO_NONE');

commit;

--更新数据
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '自动定价调用webservice异常' where ERROR_CODE = 'LNMI6001';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '获取定价参数异常'           where ERROR_CODE = 'LNMI6002';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '自动定价系统异常'           where ERROR_CODE = 'LNMI6003';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '自动定价结果XML解析异常'    where ERROR_CODE = 'LNMI6004';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '自动定价结果保存异常'       where ERROR_CODE = 'LNMI6005';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '更新申请利率表异常'         where ERROR_CODE = 'LNMI6006';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '获取辅助参数异常'           where ERROR_CODE = 'LNMI6007';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '定价结果利率为null'         where ERROR_CODE = 'LNMI6008';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '更新申请表环节异常'         where ERROR_CODE = 'LNMI6009';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '查询自动审批结果表异常'     where ERROR_CODE = 'LNMI6010';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '自动定价未知异常'           where ERROR_CODE = 'LNMI6000';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '工作流调用自动定价节点异常' where ERROR_CODE = 'LNMI6011';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '工作流调用人工审批节点异常' where ERROR_CODE = 'LNMI6012';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '工作流发起流程异常'         where ERROR_CODE = 'LNMI6013';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '工作流提交任务异常'         where ERROR_CODE = 'LNMI6014';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '工作流查询任务异常'         where ERROR_CODE = 'LNMI6015';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '工作流自动转人工审批异常'   where ERROR_CODE = 'LNMI6016';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '工作流人工审批异常'         where ERROR_CODE = 'LNMI6017';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '自动定价失败'               where ERROR_CODE = 'LNMI6018';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = 'ABIS行号为空'               where ERROR_CODE = 'LNMI6019';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = 'CIF为空'                    where ERROR_CODE = 'LNMI6020';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = 'CL/EC为空'                  where ERROR_CODE = 'LNMI6021';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '贷款申请表查询为空'         where ERROR_CODE = 'LNMI6022';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '贷款资料表查询为空'         where ERROR_CODE = 'LNMI6023';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '贷款申请利率表查询为空'     where ERROR_CODE = 'LNMI6024';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '客户评价结果表查询为空'     where ERROR_CODE = 'LNMI6025';
update CP_ERROR_INFO_COMP set ERROR_USER_DESC = '定价参数结果表查询为空'     where ERROR_CODE = 'LNMI6026';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '激活凭证-连接BOEING异常,异常原因:[{0}]',ERROR_USER_DESC = '激活凭证-连接BOEING异常,异常原因:[{0}]' where ERROR_CODE = 'LNMI8024';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '自动审批结果查询异常！'                                     , ERROR_USER_DESC = '自动审批结果查询异常！'                                      where ERROR_CODE = 'LNMI9001';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '自动审批结果不存在！'                                       , ERROR_USER_DESC = '自动审批结果不存在！'                                        where ERROR_CODE = 'LNMI9002';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '自动审批结果插入失败！'                                     , ERROR_USER_DESC = '自动审批结果插入失败！'                                      where ERROR_CODE = 'LNMI9003';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '自动审批结果更新失败！'                                     , ERROR_USER_DESC = '自动审批结果更新失败！'                                      where ERROR_CODE = 'LNMI9004';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '贷款申请信息查询异常！'                                     , ERROR_USER_DESC = '贷款申请信息查询异常！'                                      where ERROR_CODE = 'LNMI9005';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '贷款申请信息不存在！'                                       , ERROR_USER_DESC = '贷款申请信息不存在！'                                        where ERROR_CODE = 'LNMI9006';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '申请信息已失效！'                                           , ERROR_USER_DESC = '申请信息已失效！'                                            where ERROR_CODE = 'LNMI9007';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '贷款申请环节异常！'                                         , ERROR_USER_DESC = '贷款申请环节异常！'                                          where ERROR_CODE = 'LNMI9008';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '当前环节不为[{0}]，无法进行该操作！'                        , ERROR_USER_DESC = '当前环节不为[{0}]，无法进行该操作！'                         where ERROR_CODE = 'LNMI9009';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '贷款申请信息状态更新失败！'                                 , ERROR_USER_DESC = '贷款申请信息状态更新失败！'                                  where ERROR_CODE = 'LNMI9010';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '征信管理系统地址获取异常！'                                 , ERROR_USER_DESC = '征信管理系统地址获取异常！'                                  where ERROR_CODE = 'LNMI9011';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '征信管理系统服务未开放！'                                   , ERROR_USER_DESC = '征信管理系统服务未开放！'                                    where ERROR_CODE = 'LNMI9012';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '征信管理系统法人校验异常，异常代码：[{0}]，异常原因：[{1}]' , ERROR_USER_DESC = '征信管理系统法人校验异常，异常代码：[{0}]，异常原因：[{1}]'  where ERROR_CODE = 'LNMI9013';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '征信管理系统个人校验异常，异常代码：[{0}]，异常原因：[{1}]' , ERROR_USER_DESC = '征信管理系统个人校验异常，异常代码：[{0}]，异常原因：[{1}]'  where ERROR_CODE = 'LNMI9014';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '法人征信报文解析异常！'                                     , ERROR_USER_DESC = '法人征信报文解析异常！'                                      where ERROR_CODE = 'LNMI9015';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '法人征信结果返回为空！'                                     , ERROR_USER_DESC = '法人征信结果返回为空！'                                      where ERROR_CODE = 'LNMI9016';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '企业征信表信息查询异常！'                                   , ERROR_USER_DESC = '企业征信表信息查询异常！'                                    where ERROR_CODE = 'LNMI9017';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '法人征信结果过录至企业征信信息异常！'                       , ERROR_USER_DESC = '法人征信结果过录至企业征信信息异常！'                        where ERROR_CODE = 'LNMI9018';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '企业征信信息写入异常！'                                     , ERROR_USER_DESC = '企业征信信息写入异常！'                                      where ERROR_CODE = 'LNMI9019';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '企业征信信息更新异常'                                       , ERROR_USER_DESC = '企业征信信息更新异常'                                        where ERROR_CODE = 'LNMI9020';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '企业征信信息源表查询异常'                                   , ERROR_USER_DESC = '企业征信信息源表查询异常'                                    where ERROR_CODE = 'LNMI9021';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '企业征信信息过录至企业征信源信息异常'                       , ERROR_USER_DESC = '企业征信信息过录至企业征信源信息异常'                        where ERROR_CODE = 'LNMI9022';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '企业征信源信息插入异常'                                     , ERROR_USER_DESC = '企业征信源信息插入异常'                                      where ERROR_CODE = 'LNMI9023';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '企业征信校验发生未知异常'                                   , ERROR_USER_DESC = '企业征信校验发生未知异常'                                    where ERROR_CODE = 'LNMI9024';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '企业管理员（法定代表人）查询异常'                           , ERROR_USER_DESC = '企业管理员（法定代表人）查询异常'                            where ERROR_CODE = 'LNMI9025';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '法定代表人征信信息过录至法定代表人征信源信息查询异常'       , ERROR_USER_DESC = '法定代表人征信信息过录至法定代表人征信源信息查询异常'        where ERROR_CODE = 'LNMI9026';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '企业管理员（法定代表人）不存在！'                           , ERROR_USER_DESC = '企业管理员（法定代表人）不存在！'                            where ERROR_CODE = 'LNMI9027';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '法定代表人征信信息查询异常'                                 , ERROR_USER_DESC = '法定代表人征信信息查询异常'                                  where ERROR_CODE = 'LNMI9028';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '人行征信信息过录至法定代表人征信信息查询异常'               , ERROR_USER_DESC = '人行征信信息过录至法定代表人征信信息查询异常'                where ERROR_CODE = 'LNMI9029';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '法定代表人征信信息插入异常'                                 , ERROR_USER_DESC = '法定代表人征信信息插入异常'                                  where ERROR_CODE = 'LNMI9030';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '法定代表人征信信息更新异常'                                 , ERROR_USER_DESC = '法定代表人征信信息更新异常'                                  where ERROR_CODE = 'LNMI9031';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '法定代表人征信源信息查询异常'                               , ERROR_USER_DESC = '法定代表人征信源信息查询异常'                                where ERROR_CODE = 'LNMI9032';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '法定代表人征信源信息插入异常'                               , ERROR_USER_DESC = '法定代表人征信源信息插入异常'                                where ERROR_CODE = 'LNMI9033';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '法定代表人征信源信息更新异常'                               , ERROR_USER_DESC = '法定代表人征信源信息更新异常'                                where ERROR_CODE = 'LNMI9034';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '法定代表人征信校验发生未知异常'                             , ERROR_USER_DESC = '法定代表人征信校验发生未知异常'                              where ERROR_CODE = 'LNMI9035';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '审批登记信息不存在'                                         , ERROR_USER_DESC = '审批登记信息不存在'                                          where ERROR_CODE = 'LNMI9036';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '贷款资料信息不存在！'                                       , ERROR_USER_DESC = '贷款资料信息不存在！'                                        where ERROR_CODE = 'LNMI9037';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '定价结果不存在！'                                           , ERROR_USER_DESC = '定价结果不存在！'                                            where ERROR_CODE = 'LNMI9038';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '人工审批时间格式错误！'                                     , ERROR_USER_DESC = '人工审批时间格式错误！'                                      where ERROR_CODE = 'LNMI9039';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '自动审批时间格式错误！'                                     , ERROR_USER_DESC = '自动审批时间格式错误！'                                      where ERROR_CODE = 'LNMI9040';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '审批机构不存在！'                                           , ERROR_USER_DESC = '审批机构不存在！'                                            where ERROR_CODE = 'LNMI9041';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3服务地址不存在！'                                         , ERROR_USER_DESC = 'C3服务地址不存在！'                                          where ERROR_CODE = 'LNMI9042';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3返回结果为空！'                                           , ERROR_USER_DESC = 'C3返回结果为空！'                                            where ERROR_CODE = 'LNMI9043';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3返回XML解析异常！'                                        , ERROR_USER_DESC = 'C3返回XML解析异常！'                                         where ERROR_CODE = 'LNMI9044';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '审批登记信息更新失败！'                                     , ERROR_USER_DESC = '审批登记信息更新失败！'                                      where ERROR_CODE = 'LNMI9045';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3对照关系信息查询失败！'                                   , ERROR_USER_DESC = 'C3对照关系信息查询失败！'                                    where ERROR_CODE = 'LNMI9046';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3对照关系信息更新失败！'                                   , ERROR_USER_DESC = 'C3对照关系信息更新失败！'                                    where ERROR_CODE = 'LNMI9047';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3对照关系信息写入失败！'                                   , ERROR_USER_DESC = 'C3对照关系信息写入失败！'                                    where ERROR_CODE = 'LNMI9048';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '贷款申请利率信息查询失败！'                                 , ERROR_USER_DESC = '贷款申请利率信息查询失败！'                                  where ERROR_CODE = 'LNMI9049';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '贷款申请利率信息不存在！'                                   , ERROR_USER_DESC = '贷款申请利率信息不存在！'                                    where ERROR_CODE = 'LNMI9050';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '定价结果更新失败'                                           , ERROR_USER_DESC = '定价结果更新失败'                                            where ERROR_CODE = 'LNMI9051';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3服务未开放或连接超时！'                                   , ERROR_USER_DESC = 'C3服务未开放或连接超时！'                                    where ERROR_CODE = 'LNMI9052';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3远程服务异常！'                                           , ERROR_USER_DESC = 'C3远程服务异常！'                                            where ERROR_CODE = 'LNMI9053';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3URL解析异常！'                                            , ERROR_USER_DESC = 'C3URL解析异常！'                                             where ERROR_CODE = 'LNMI9054';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3服务对象生成异常！'                                       , ERROR_USER_DESC = 'C3服务对象生成异常！'                                        where ERROR_CODE = 'LNMI9055';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '审批登记查询异常'                                           , ERROR_USER_DESC = '审批登记查询异常'                                            where ERROR_CODE = 'LNMI9056';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '客户贷款信息查询异常'                                       , ERROR_USER_DESC = '客户贷款信息查询异常'                                        where ERROR_CODE = 'LNMI9057';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '人工审批结果查询异常'                                       , ERROR_USER_DESC = '人工审批结果查询异常'                                        where ERROR_CODE = 'LNMI9058';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '定价结果查询异常'                                           , ERROR_USER_DESC = '定价结果查询异常'                                            where ERROR_CODE = 'LNMI9059';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '借款合同查询异常'                                           , ERROR_USER_DESC = '借款合同查询异常'                                            where ERROR_CODE = 'LNMI9060';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '借款合同写入异常'                                           , ERROR_USER_DESC = '借款合同写入异常'                                            where ERROR_CODE = 'LNMI9061';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '借款合同更新异常'                                           , ERROR_USER_DESC = '借款合同更新异常'                                            where ERROR_CODE = 'LNMI9062';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3对照关系信息不存在'                                       , ERROR_USER_DESC = 'C3对照关系信息不存在'                                        where ERROR_CODE = 'LNMI9063';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '利率信息写入异常'                                           , ERROR_USER_DESC = '利率信息写入异常'                                            where ERROR_CODE = 'LNMI9064';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3新增审批登记信息异常，异常代码：[{0}],异常原因：[{1}]'    , ERROR_USER_DESC = 'C3新增审批登记信息异常，异常代码：[{0}],异常原因：[{1}]'     where ERROR_CODE = 'LNMI9065';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3新增借款合同信息异常，异常代码：[{0}],异常原因：[{1}]'    , ERROR_USER_DESC = 'C3新增借款合同信息异常，异常代码：[{0}],异常原因：[{1}]'     where ERROR_CODE = 'LNMI9066';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3新增借款合同利率信息异常，异常代码：[{0}],异常原因：[{1}]', ERROR_USER_DESC = 'C3新增借款合同利率信息异常，异常代码：[{0}],异常原因：[{1}]' where ERROR_CODE = 'LNMI9067';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '借款合同信息不存在'                                         , ERROR_USER_DESC = '借款合同信息不存在'                                          where ERROR_CODE = 'LNMI9068';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '借款合同信息查询异常'                                       , ERROR_USER_DESC = '借款合同信息查询异常'                                        where ERROR_CODE = 'LNMI9069';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '借款合同状态不为登记，无法生效'                             , ERROR_USER_DESC = '借款合同状态不为登记，无法生效'                              where ERROR_CODE = 'LNMI9070';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = '借款合同更新失败'                                           , ERROR_USER_DESC = '借款合同更新失败'                                            where ERROR_CODE = 'LNMI9071';
update CP_ERROR_INFO_COMP set ERROR_SYS_DESC = 'C3借款合同生效异常，异常代码：[{0}],异常原因：[{1}]'        , ERROR_USER_DESC = 'C3借款合同生效异常，异常代码：[{0}],异常原因：[{1}]'         where ERROR_CODE = 'LNMI9072';
commit;
