--删除可能存在的数据
--delete from CP_MSG_TEMPLATE where template_code like 'LN_%';
--commit;

--写入数据
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_APP_FIL', '通知客户经理审核贷款资料', '待审核贷款资料', '<p>${managerName}您好，您的客户${enterName}已经提交贷款资料，请尽快审核！</p>', 'LN', 2, 2, '0', null, null, null, null, '1', null, '企业客户提交贷款信息后，向ERP客户经理发送短信提示尽快审批。', '1', '04', '2', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_CK_AE', '复核通过待提交审批消息模板', '复核通过待提交审批消息', '<p>尊敬的${userName}：您好。贵公司的贷款申请（编号${loanApplyNo}）已经复核通过，请及时登录我行互联网银行系统进行提交审批处理。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '贷款复核通过后需给操作员发送消息。', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_FIL_PST', '贷款资料审核通过通知', '通知', '<p>尊敬的客户，您提交的贷款资料已经审核通过，现在可以登录我行互联网银行系统进行贷款申请。</p>', 'LN', 2, 2, '0', '08:00', '22:00', null, null, '1', null, null, '1', '04', null, null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_AAI1', '自动审批通过消息模板', '自动审批通过发送消息', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）已通过审批，请登录中国农业银行农银通查看详细信息，为避免申请失效，请尽快确认审批结果。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批通过后,发送通过消息', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_AAI2', '自动审批拒绝消息模板', '自动审批拒绝后发送消息', '<p>尊敬的${userName}：您好，抱歉的通知您，您的贷款申请（编号${loanApplyNo}）未能通过审批，请登录中国农业银行农银通查看详细信息。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批拒绝后,发送消息', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_AAI3', '自动审批需人工处理消息模板', '自动审批需人工处理消息', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）需要我行审批人员人工审批，我们将及时反馈审批结果，请您耐心等待。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批状态为需人工处理时,发送消息', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_AAM4', '自动审批需转人工处理消息模板', '自动审批需转人工处理消息', '<p>尊敬的${admmgrName}：您好，客户${entName}的贷款申请（编号${loanApplyNo}）需要提交人工审批，请及时登录我行互联网银行系统进行处理。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '贷款自动审批后需转人工审批时给客户经理发送消息。', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_AARI', '确认审批结果后签订合同消息模板', '确认审批结果后签订合同消息', '<p>尊敬的${userName}：您好，您已确认贷款申请（编号${loanApplyNo}）的审批结果，为避免申请失效，请尽快签订合同。谢谢！</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '确认审批结果后签订合同消息', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_ATME', '自动转人工审批邮件信息模板', '自动转人工审批邮件信息', '<p>尊敬的${userName}：您好，客户${entName}的贷款申请(编号${loanApplyNo})需要你人工审批，请及时登录我行互联网银行系统进行处理。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批转人工审批操作后，给审批人发送邮件。', '1', '04', '3', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_ATMI', '自动转人工审批站内消息模板', '自动审批转人工审批消息', '<p>尊敬的${userName}：您好，客户${entName}的贷款申请(编号${loanApplyNo})需要你人工审批，请及时登录我行互联网银行系统进行处理。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批转人工审批，给审批人发送消息', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_ATMM', '自动转人工审批短信信息模板', '自动转人工审批短信信息', '<p>尊敬的${userName}：您好，客户${entName}的贷款申请(编号${loanApplyNo})需要你人工审批，请及时登录我行互联网银行系统进行处理。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '自动审批转人工审批操作后，给审批人发送短信。', '1', '04', '2', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAE1', '人工审批通过时发送邮件模版', '人工审批通过时发送审批通过邮件', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）已通过审批，请登录中国农业银行农银通查询详细信息，为避免申请失效，请尽快确认审批结果。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '人工审批后，给用户发送审批结果，审批通过后提示用户确认审批结果。', '1', '04', '3', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAE2', '人工审批拒绝时发送邮件模版', '人工审批拒绝时发送邮件', '<p>尊敬的${userName}：您好，抱歉的通知您，您的贷款申请（编号${loanApplyNo}）未能通过审批，请登录中国农业银行农银通查看详细信息。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '审批不通过： 人工审批后，给用户发送审批结果，审批不通过，则通知用户审批不通过信息。', '1', '04', '3', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAI1', '人工审批通过时发送消息模版', '人工审批通过时发送审批通过消息', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）已通过审批，请登录中国农业银行农银通查询详细信息，为避免申请失效，请尽快确认审批结果。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '人工审批后，给用户发送审批结果，审批通过后提示用户确认审批结果。', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAI2', '人工审批拒绝时发送消息模版', '人工审批拒绝时发送消息', '<p>尊敬的${userName}：您好，抱歉的通知您，您的贷款申请（编号${loanApplyNo}）未能通过审批，请登录中国农业银行农银通查看详细信息。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '人工审批后，给用户发送审批结果，审批不通过，提示用户审批不通过信息。', '1', '04', '1', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAM1', '人工审批通过时发送短信模版', '人工审批通过时发送短信', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）已通过审批，请登录中国农业银行农银通查看详细信息，为避免申请失效，请尽快确认审批结果。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '人工审批后，给用户发送审批结果，审批通过后提示用户确认审批结果。', '1', '04', '2', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_MI_MAM2', '人工审批拒绝时发送短信模版', '人工审批拒绝时发送短信', '<p>尊敬的${userName}：您好，抱歉的通知您，您的贷款申请（编号${loanApplyNo}）未能通过审批，请登录中国农业银行农银通查看详细信息。</p>', 'LN', 3, 3, '0', '08:00', '22:00', null, null, '1', null, '人工审批后，给用户发送审批结果，审批不通过，则通知用户审批不通过信息。', '1', '04', '2', null);
insert into cp_msg_template (TEMPLATE_CODE, TEMPLATE_NAME, MSG_SUBJECT, MSG_CONTENT, PRODUCT_CODE, SEND_LEVEL, DISP_LEVEL, TIME_FLAG, START_TIME1, END_TIME1, START_TIME2, END_TIME2, WEEKEND_FLAG, HOLIDAY_FLAG, DESCRIPTION, TEMPLATE_STATUS, MSG_TYPE, MSG_CHANNEL, TRANS_CODE) values ('LN_SGN_CNT', '合同签订消息', '签约合同成功', '<p>尊敬的${userName}：您好，您的贷款申请（编号${loanApplyNo}）签约合同成功，正进入放款阶段，请登录系统查看详情。</p>', 'LN', 3, 3, '0', '08:00', '10:00', '08:00', '22:00', '1', null, '签约合同成功消息', '1', '04', null, null);
commit;
