---
- name: start docker
  command: /bin/true
  notify:
    - reload systemd
    - reload docker

- name: reload systemd
  command: systemctl daemon-reload

- name: reload docker
  service:
    name: docker
    status: restart
