/*==============================================================*/
/* DBMS name:      ORACLE Version 10g                           */
/* Created on:     2014/1/8 16:52:23                            */
/*==============================================================*/


DROP INDEX "IDX_EP_ABIS_TRACE2";

DROP INDEX "IDX_EP_ABIS_TRACE";

ALTER TABLE "EP_ABIS_TRACE"
   DROP PRIMARY KEY CASCADE;

DROP TABLE "EP_ABIS_TRACE" CASCADE CONSTRAINTS;

DROP INDEX "INDEX_2";

DROP INDEX "IDX_EP_ACCOUNT_TRACE1";

ALTER TABLE "EP_ACCOUNT_TRACE"
   DROP PRIMARY KEY CASCADE;

DROP TABLE "EP_ACCOUNT_TRACE" CASCADE CONSTRAINTS;

DROP INDEX "IDX_EP_ACCT_TRACE2";

DROP INDEX "IDX_EP_ACCT_TRACE1";

ALTER TABLE "EP_ACCT_TRACE"
   DROP PRIMARY KEY CASCADE;

DROP TABLE "EP_ACCT_TRACE" CASCADE CONSTRAINTS;

DROP INDEX "IDX_EP_B2C_TRACE2";

DROP INDEX "IDX_EP_B2C_TRACE1";

ALTER TABLE "EP_B2C_TRACE"
   DROP PRIMARY KEY CASCADE;

DROP TABLE "EP_B2C_TRACE" CASCADE CONSTRAINTS;

DROP INDEX "IDX_EP_BOEING_TRACE2";

DROP INDEX "IDX_EP_BOEING_TRACE1";

ALTER TABLE "EP_BOEING_TRACE"
   DROP PRIMARY KEY CASCADE;

DROP TABLE "EP_BOEING_TRACE" CASCADE CONSTRAINTS;

DROP INDEX "IDX_EP_DEPOSIT_ACCT_TRACE2";

DROP INDEX "IDX_EP_DEPOSIT_ACCT_TRACE1";

ALTER TABLE "EP_DEPOSIT_ACCT_TRACE"
   DROP PRIMARY KEY CASCADE;

DROP TABLE "EP_DEPOSIT_ACCT_TRACE" CASCADE CONSTRAINTS;

DROP INDEX "IDX_EP_INTS_TRACE2";

DROP INDEX "IDX_EP_INTS _TRACE1";

ALTER TABLE "EP_INTS_TRACE"
   DROP PRIMARY KEY CASCADE;

DROP TABLE "EP_INTS_TRACE" CASCADE CONSTRAINTS;

DROP INDEX "IDX_EP_MARKET_TRACE2";

DROP INDEX "IDX_EP_MARKET _TRACE1";

ALTER TABLE "EP_MARKET_TRACE"
   DROP PRIMARY KEY CASCADE;

DROP TABLE "EP_MARKET_TRACE" CASCADE CONSTRAINTS;

DROP INDEX "IDX_EP_ORDER_TRACE4";

DROP INDEX "IDX_EP_ORDER_TRACE3";

DROP INDEX "IDX_EP_ORDER_TRACE2";

ALTER TABLE "EP_ORDER_TRACE"
   DROP PRIMARY KEY CASCADE;

DROP TABLE "EP_ORDER_TRACE" CASCADE CONSTRAINTS;

/*==============================================================*/
/* Table: "EP_ABIS_TRACE"                                       */
/*==============================================================*/
CREATE TABLE "EP_ABIS_TRACE"  (
   USER_NO              VARCHAR2(128),
   ACCT_NO              VARCHAR2(32),
   SYS_SEQ              VARCHAR2(32)                    NOT NULL,
   SET_DATE             VARCHAR2(8),
   TRANS_ACCT_NO        VARCHAR2(32),
   TRANS_DATE           VARCHAR2(8),
   TRANS_TIME           VARCHAR2(6),
   TRANS_TYPE           VARCHAR2(6),
   SYS_MERCH_NO         VARCHAR2(15),
   MERCH_ORDERNO        VARCHAR2(32),
   EXT_ACCT_NO          VARCHAR2(32),
   TRANS_CURR           VARCHAR2(3),
   TRANS_STAT           CHAR(1),
   TRANS_AMT            NUMBER(25,2),
   TRANS_FEE            NUMBER(25,2),
   ABIS_SEQ             VARCHAR2(32),
   LOG_NUMBER           VARCHAR2(32),
   SUMMONS_NUM          VARCHAR2(32),
   DC_FLAG              CHAR(1),
   RB_FLAG              CHAR(1),
   TRANS_NATURE         CHAR(1),
   BACKGROUND_DATE      VARCHAR2(8),
   RESP_CODE            VARCHAR2(8),
   RESP_MSG             VARCHAR2(192),
   REMARK               VARCHAR2(192)
)
PARTITION BY RANGE (TRANS_DATE)(
	PARTITION PP201401 VALUES LESS THAN ('20140201') TABLESPACE P201401,
	PARTITION PP201402 VALUES LESS THAN ('20140301') TABLESPACE P201402,
	PARTITION PP201403 VALUES LESS THAN ('20140401') TABLESPACE P201403,
	PARTITION PP201404 VALUES LESS THAN ('20140501') TABLESPACE P201404,
	PARTITION PP201405 VALUES LESS THAN ('20140601') TABLESPACE P201405,
	PARTITION PP201406 VALUES LESS THAN ('20140701') TABLESPACE P201406,
	PARTITION PP201407 VALUES LESS THAN ('20140801') TABLESPACE P201407,
	PARTITION PP201408 VALUES LESS THAN ('20140901') TABLESPACE P201408,
	PARTITION PP201409 VALUES LESS THAN ('20141001') TABLESPACE P201409,
	PARTITION PP201410 VALUES LESS THAN ('20141101') TABLESPACE P201410,
	PARTITION PP201411 VALUES LESS THAN ('20141201') TABLESPACE P201411,
	PARTITION PP201412 VALUES LESS THAN ('99999999') TABLESPACE P201412
);

COMMENT ON TABLE "EP_ABIS_TRACE" IS
'ABIS渠道流水';

COMMENT ON COLUMN "EP_ABIS_TRACE".USER_NO IS
'用户ID';

COMMENT ON COLUMN "EP_ABIS_TRACE".ACCT_NO IS
'账号';

COMMENT ON COLUMN "EP_ABIS_TRACE".SYS_SEQ IS
'支付平台流水号';

COMMENT ON COLUMN "EP_ABIS_TRACE".SET_DATE IS
'清算日期';

COMMENT ON COLUMN "EP_ABIS_TRACE".TRANS_ACCT_NO IS
'交易帐号';

COMMENT ON COLUMN "EP_ABIS_TRACE".TRANS_DATE IS
'交易日期';

COMMENT ON COLUMN "EP_ABIS_TRACE".TRANS_TIME IS
'交易时间';

COMMENT ON COLUMN "EP_ABIS_TRACE".TRANS_TYPE IS
'交易类型';

COMMENT ON COLUMN "EP_ABIS_TRACE".SYS_MERCH_NO IS
'商户编号';

COMMENT ON COLUMN "EP_ABIS_TRACE".MERCH_ORDERNO IS
'商户订单号';

COMMENT ON COLUMN "EP_ABIS_TRACE".EXT_ACCT_NO IS
'扩展帐号';

COMMENT ON COLUMN "EP_ABIS_TRACE".TRANS_CURR IS
'交易币种(RMB-156)：RMB、EUR、USD';

COMMENT ON COLUMN "EP_ABIS_TRACE".TRANS_STAT IS
'订单状态：0、成功；1、初始；2、失败； 3、撤销';

COMMENT ON COLUMN "EP_ABIS_TRACE".TRANS_AMT IS
'交易金额';

COMMENT ON COLUMN "EP_ABIS_TRACE".TRANS_FEE IS
'交易手续费';

COMMENT ON COLUMN "EP_ABIS_TRACE".ABIS_SEQ IS
'ABIS流水号';

COMMENT ON COLUMN "EP_ABIS_TRACE".LOG_NUMBER IS
'A系统日志号';

COMMENT ON COLUMN "EP_ABIS_TRACE".SUMMONS_NUM IS
'A系统传票号';

COMMENT ON COLUMN "EP_ABIS_TRACE".DC_FLAG IS
'借贷标志：D、借；C、贷';

COMMENT ON COLUMN "EP_ABIS_TRACE".RB_FLAG IS
'红蓝标志：R、红；B、蓝';

COMMENT ON COLUMN "EP_ABIS_TRACE".TRANS_NATURE IS
'交易性质：1、正常；2、抹账';

COMMENT ON COLUMN "EP_ABIS_TRACE".BACKGROUND_DATE IS
'后台清算日期';

COMMENT ON COLUMN "EP_ABIS_TRACE".RESP_CODE IS
'响应码';

COMMENT ON COLUMN "EP_ABIS_TRACE".RESP_MSG IS
'响应信息';

COMMENT ON COLUMN "EP_ABIS_TRACE".REMARK IS
'备注信息';

ALTER TABLE "EP_ABIS_TRACE"
   ADD CONSTRAINT PK_EP_ABIS_TRACE PRIMARY KEY (SYS_SEQ);

/*==============================================================*/
/* Index: "IDX_EP_ABIS_TRACE"                                   */
/*==============================================================*/
CREATE UNIQUE INDEX "IDX_EP_ABIS_TRACE" ON "EP_ABIS_TRACE" (
   ACCT_NO ASC,
   SYS_SEQ ASC,
   SET_DATE ASC
);

/*==============================================================*/
/* Index: "IDX_EP_ABIS_TRACE2"                                  */
/*==============================================================*/
CREATE UNIQUE INDEX "IDX_EP_ABIS_TRACE2" ON "EP_ABIS_TRACE" (
   USER_NO ASC,
   TRANS_DATE ASC,
   SYS_MERCH_NO ASC,
   MERCH_ORDERNO ASC
);

/*==============================================================*/
/* Table: "EP_ACCOUNT_TRACE"                                    */
/*==============================================================*/
CREATE TABLE "EP_ACCOUNT_TRACE"  (
   ID                   VARCHAR2(32)                    NOT NULL,
   ACCT_NO              VARCHAR2(32),
   SUBJECT_NO           VARCHAR2(10),
   TRANS_DATE           VARCHAR2(8),
   TRANS_TIME           VARCHAR2(6),
   SYS_SEQ              VARCHAR2(32),
   SET_DATE             VARCHAR2(8),
   TRANS_TYPE           VARCHAR2(6),
   DC_FLAG              CHAR(1),
   TRANS_CURR           VARCHAR2(3),
   TRANS_AMT            NUMBER(25,2),
   TRANS_FLAG           CHAR(1),
   REMARK               VARCHAR2(192)
)
PARTITION BY RANGE (TRANS_DATE)(
	PARTITION PP201401 VALUES LESS THAN ('20140201') TABLESPACE P201401,
	PARTITION PP201402 VALUES LESS THAN ('20140301') TABLESPACE P201402,
	PARTITION PP201403 VALUES LESS THAN ('20140401') TABLESPACE P201403,
	PARTITION PP201404 VALUES LESS THAN ('20140501') TABLESPACE P201404,
	PARTITION PP201405 VALUES LESS THAN ('20140601') TABLESPACE P201405,
	PARTITION PP201406 VALUES LESS THAN ('20140701') TABLESPACE P201406,
	PARTITION PP201407 VALUES LESS THAN ('20140801') TABLESPACE P201407,
	PARTITION PP201408 VALUES LESS THAN ('20140901') TABLESPACE P201408,
	PARTITION PP201409 VALUES LESS THAN ('20141001') TABLESPACE P201409,
	PARTITION PP201410 VALUES LESS THAN ('20141101') TABLESPACE P201410,
	PARTITION PP201411 VALUES LESS THAN ('20141201') TABLESPACE P201411,
	PARTITION PP201412 VALUES LESS THAN ('99999999') TABLESPACE P201412
);

COMMENT ON TABLE "EP_ACCOUNT_TRACE" IS
'会计账务流水表';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".ID IS
'主键ID';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".ACCT_NO IS
'账号';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".SUBJECT_NO IS
'贷方科目号';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".TRANS_DATE IS
'交易日期';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".TRANS_TIME IS
'交易时间';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".SYS_SEQ IS
'支付平台流水号';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".SET_DATE IS
'清算日期';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".TRANS_TYPE IS
'交易类型';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".DC_FLAG IS
'借贷标志：D、借；C、贷';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".TRANS_CURR IS
'交易币种(RMB-156)：RMB(156)、EUR、USD';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".TRANS_AMT IS
'交易金额';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".TRANS_FLAG IS
'交易标志：1、正常；2、抹账';

COMMENT ON COLUMN "EP_ACCOUNT_TRACE".REMARK IS
'备注';

ALTER TABLE "EP_ACCOUNT_TRACE"
   ADD CONSTRAINT PK_EP_ACCOUNT_TRACE PRIMARY KEY (ID);

/*==============================================================*/
/* Index: "IDX_EP_ACCOUNT_TRACE1"                               */
/*==============================================================*/
CREATE INDEX "IDX_EP_ACCOUNT_TRACE1" ON "EP_ACCOUNT_TRACE" (
   ACCT_NO ASC,
   SYS_SEQ ASC,
   SET_DATE ASC,
   DC_FLAG ASC
);

/*==============================================================*/
/* Index: "INDEX_2"                                             */
/*==============================================================*/
CREATE INDEX "INDEX_2" ON "EP_ACCOUNT_TRACE" (
   ACCT_NO ASC
);

/*==============================================================*/
/* Table: "EP_ACCT_TRACE"                                       */
/*==============================================================*/
CREATE TABLE "EP_ACCT_TRACE"  (
   ID                   VARCHAR2(32)                    NOT NULL,
   ACCT_NO              VARCHAR2(32),
   TRANS_DATE           VARCHAR2(8),
   TRANS_TIME           VARCHAR2(6),
   TRANS_TYPE           VARCHAR2(6),
   SYS_SEQ              VARCHAR2(32),
   SET_DATE             VARCHAR2(8),
   DC_FLAG              CHAR(1),
   TRANS_CURR           VARCHAR2(3),
   TRANS_AMT            NUMBER(25,2),
   MERCH_NO             VARCHAR2(15),
   MERCH_ORDERNO        VARCHAR2(32),
   IN_ACCT_NO           VARCHAR2(32),
   RB_FLAG              CHAR(1),
   ACCOUNTING_TYPE      CHAR(1),
   REMARK               VARCHAR2(192)
)
PARTITION BY RANGE (TRANS_DATE)(
	PARTITION PP201401 VALUES LESS THAN ('20140201') TABLESPACE P201401,
	PARTITION PP201402 VALUES LESS THAN ('20140301') TABLESPACE P201402,
	PARTITION PP201403 VALUES LESS THAN ('20140401') TABLESPACE P201403,
	PARTITION PP201404 VALUES LESS THAN ('20140501') TABLESPACE P201404,
	PARTITION PP201405 VALUES LESS THAN ('20140601') TABLESPACE P201405,
	PARTITION PP201406 VALUES LESS THAN ('20140701') TABLESPACE P201406,
	PARTITION PP201407 VALUES LESS THAN ('20140801') TABLESPACE P201407,
	PARTITION PP201408 VALUES LESS THAN ('20140901') TABLESPACE P201408,
	PARTITION PP201409 VALUES LESS THAN ('20141001') TABLESPACE P201409,
	PARTITION PP201410 VALUES LESS THAN ('20141101') TABLESPACE P201410,
	PARTITION PP201411 VALUES LESS THAN ('20141201') TABLESPACE P201411,
	PARTITION PP201412 VALUES LESS THAN ('99999999') TABLESPACE P201412
);

COMMENT ON TABLE "EP_ACCT_TRACE" IS
'虚拟账户流水表';

COMMENT ON COLUMN "EP_ACCT_TRACE".ACCT_NO IS
'账号';

COMMENT ON COLUMN "EP_ACCT_TRACE".TRANS_DATE IS
'交易日期';

COMMENT ON COLUMN "EP_ACCT_TRACE".TRANS_TIME IS
'交易时间';

COMMENT ON COLUMN "EP_ACCT_TRACE".TRANS_TYPE IS
'交易类型';

COMMENT ON COLUMN "EP_ACCT_TRACE".SYS_SEQ IS
'支付平台流水号';

COMMENT ON COLUMN "EP_ACCT_TRACE".SET_DATE IS
'清算日期';

COMMENT ON COLUMN "EP_ACCT_TRACE".DC_FLAG IS
'借贷标志：D、借；C、贷';

COMMENT ON COLUMN "EP_ACCT_TRACE".TRANS_CURR IS
'交易币种';

COMMENT ON COLUMN "EP_ACCT_TRACE".TRANS_AMT IS
'交易金额';

COMMENT ON COLUMN "EP_ACCT_TRACE".MERCH_NO IS
'商户号';

COMMENT ON COLUMN "EP_ACCT_TRACE".MERCH_ORDERNO IS
'商户订单号';

COMMENT ON COLUMN "EP_ACCT_TRACE".IN_ACCT_NO IS
'贷方帐号';

COMMENT ON COLUMN "EP_ACCT_TRACE".RB_FLAG IS
'红蓝标志：1、红；2、蓝';

COMMENT ON COLUMN "EP_ACCT_TRACE".ACCOUNTING_TYPE IS
'交易性质：1、正常；2、抹账；3、被抹';

COMMENT ON COLUMN "EP_ACCT_TRACE".REMARK IS
'备注';

ALTER TABLE "EP_ACCT_TRACE"
   ADD CONSTRAINT PK_EP_ACCT_TRACE PRIMARY KEY (ID);

/*==============================================================*/
/* Index: "IDX_EP_ACCT_TRACE1"                                  */
/*==============================================================*/
CREATE INDEX "IDX_EP_ACCT_TRACE1" ON "EP_ACCT_TRACE" (
   ACCT_NO ASC,
   SYS_SEQ ASC,
   SET_DATE ASC
);

/*==============================================================*/
/* Index: "IDX_EP_ACCT_TRACE2"                                  */
/*==============================================================*/
CREATE INDEX "IDX_EP_ACCT_TRACE2" ON "EP_ACCT_TRACE" (
   ID ASC
);

/*==============================================================*/
/* Table: "EP_B2C_TRACE"                                        */
/*==============================================================*/
CREATE TABLE "EP_B2C_TRACE"  (
   USER_NO              VARCHAR2(128),
   ACCT_NO              VARCHAR2(32),
   SYS_SEQ              VARCHAR2(32)                    NOT NULL,
   SET_DATE             VARCHAR2(8),
   TRANS_ACCT_NO        VARCHAR2(32),
   TRANS_DATE           VARCHAR2(8),
   TRANS_TIME           VARCHAR2(6),
   TRANS_TYPE           VARCHAR2(6),
   SYS_MERCH_NO         VARCHAR2(15),
   MERCH_ORDERNO        VARCHAR2(32),
   EXT_ACCT_NO          VARCHAR2(32),
   TRANS_CURR           VARCHAR2(3),
   TRANS_STAT           CHAR(1),
   TRANS_AMT            NUMBER(25,2),
   TRANS_FEE            NUMBER(25,2),
   B2C_SEQ              VARCHAR2(32),
   LOG_NUMBER           VARCHAR2(32),
   SUMMONS_NUM          VARCHAR2(32),
   DC_FLAG              CHAR(1),
   RB_FLAG              CHAR(1),
   TRANS_NATURE         CHAR(1),
   BACKGROUND_DATE      VARCHAR2(8),
   RESP_CODE            VARCHAR2(6),
   RESP_MSG             VARCHAR2(192),
   REMARK               VARCHAR2(192)
)
PARTITION BY RANGE (TRANS_DATE)(
	PARTITION PP201401 VALUES LESS THAN ('20140201') TABLESPACE P201401,
	PARTITION PP201402 VALUES LESS THAN ('20140301') TABLESPACE P201402,
	PARTITION PP201403 VALUES LESS THAN ('20140401') TABLESPACE P201403,
	PARTITION PP201404 VALUES LESS THAN ('20140501') TABLESPACE P201404,
	PARTITION PP201405 VALUES LESS THAN ('20140601') TABLESPACE P201405,
	PARTITION PP201406 VALUES LESS THAN ('20140701') TABLESPACE P201406,
	PARTITION PP201407 VALUES LESS THAN ('20140801') TABLESPACE P201407,
	PARTITION PP201408 VALUES LESS THAN ('20140901') TABLESPACE P201408,
	PARTITION PP201409 VALUES LESS THAN ('20141001') TABLESPACE P201409,
	PARTITION PP201410 VALUES LESS THAN ('20141101') TABLESPACE P201410,
	PARTITION PP201411 VALUES LESS THAN ('20141201') TABLESPACE P201411,
	PARTITION PP201412 VALUES LESS THAN ('99999999') TABLESPACE P201412
);

COMMENT ON TABLE "EP_B2C_TRACE" IS
'B2C渠道流水';

COMMENT ON COLUMN "EP_B2C_TRACE".USER_NO IS
'用户ID';

COMMENT ON COLUMN "EP_B2C_TRACE".ACCT_NO IS
'账号';

COMMENT ON COLUMN "EP_B2C_TRACE".SYS_SEQ IS
'支付平台流水号';

COMMENT ON COLUMN "EP_B2C_TRACE".SET_DATE IS
'清算日期';

COMMENT ON COLUMN "EP_B2C_TRACE".TRANS_ACCT_NO IS
'交易帐号';

COMMENT ON COLUMN "EP_B2C_TRACE".TRANS_DATE IS
'交易日期';

COMMENT ON COLUMN "EP_B2C_TRACE".TRANS_TIME IS
'交易时间';

COMMENT ON COLUMN "EP_B2C_TRACE".TRANS_TYPE IS
'交易类型';

COMMENT ON COLUMN "EP_B2C_TRACE".SYS_MERCH_NO IS
'商户编号';

COMMENT ON COLUMN "EP_B2C_TRACE".MERCH_ORDERNO IS
'外部订单号';

COMMENT ON COLUMN "EP_B2C_TRACE".EXT_ACCT_NO IS
'扩展帐号';

COMMENT ON COLUMN "EP_B2C_TRACE".TRANS_CURR IS
'交易币种(RMB-156)：RMB、EUR、USD';

COMMENT ON COLUMN "EP_B2C_TRACE".TRANS_STAT IS
'订单状态：0、成功；1、初始；2、失败； 3、撤销';

COMMENT ON COLUMN "EP_B2C_TRACE".TRANS_AMT IS
'交易金额';

COMMENT ON COLUMN "EP_B2C_TRACE".TRANS_FEE IS
'交易手续费';

COMMENT ON COLUMN "EP_B2C_TRACE".B2C_SEQ IS
'B2C流水号';

COMMENT ON COLUMN "EP_B2C_TRACE".LOG_NUMBER IS
'日志号';

COMMENT ON COLUMN "EP_B2C_TRACE".SUMMONS_NUM IS
'传票号';

COMMENT ON COLUMN "EP_B2C_TRACE".DC_FLAG IS
'借贷标志：D、借；C、贷';

COMMENT ON COLUMN "EP_B2C_TRACE".RB_FLAG IS
'红蓝标志：R、红；B、蓝';

COMMENT ON COLUMN "EP_B2C_TRACE".TRANS_NATURE IS
'交易性质：1、正常；2、抹账';

COMMENT ON COLUMN "EP_B2C_TRACE".BACKGROUND_DATE IS
'后台清算日期';

COMMENT ON COLUMN "EP_B2C_TRACE".RESP_CODE IS
'响应码';

COMMENT ON COLUMN "EP_B2C_TRACE".RESP_MSG IS
'响应信息';

COMMENT ON COLUMN "EP_B2C_TRACE".REMARK IS
'备注信息';

ALTER TABLE "EP_B2C_TRACE"
   ADD CONSTRAINT PK_EP_B2C_TRACE PRIMARY KEY (SYS_SEQ);

/*==============================================================*/
/* Index: "IDX_EP_B2C_TRACE1"                                   */
/*==============================================================*/
CREATE UNIQUE INDEX "IDX_EP_B2C_TRACE1" ON "EP_B2C_TRACE" (
   ACCT_NO ASC,
   SYS_SEQ ASC,
   SET_DATE ASC
);

/*==============================================================*/
/* Index: "IDX_EP_B2C_TRACE2"                                   */
/*==============================================================*/
CREATE UNIQUE INDEX "IDX_EP_B2C_TRACE2" ON "EP_B2C_TRACE" (
   USER_NO ASC,
   TRANS_DATE ASC,
   SYS_MERCH_NO ASC,
   MERCH_ORDERNO ASC
);

/*==============================================================*/
/* Table: "EP_BOEING_TRACE"                                     */
/*==============================================================*/
CREATE TABLE "EP_BOEING_TRACE"  (
   USER_NO              VARCHAR2(128),
   ACCT_NO              VARCHAR2(32),
   SYS_SEQ              VARCHAR2(32)                    NOT NULL,
   SET_DATE             VARCHAR2(8),
   TRANS_ACCT_NO        VARCHAR2(32),
   TRANS_DATE           VARCHAR2(8),
   TRANS_TIME           VARCHAR2(6),
   TRANS_TYPE           VARCHAR2(6),
   SYS_MERCH_NO         VARCHAR2(15),
   MERCH_ORDERNO        VARCHAR2(32),
   EXT_ACCT_NO          VARCHAR2(32),
   TRANS_CURR           VARCHAR2(3),
   TRANS_STAT           CHAR(1),
   TRANS_AMT            NUMBER(25,2),
   TRANS_FEE            NUMBER(25,2),
   BOEING_SEQ           VARCHAR2(32),
   LOG_NUMBER           VARCHAR2(32),
   SUMMONS_NUM          VARCHAR2(32),
   DC_FLAG              CHAR(1),
   RB_FLAG              CHAR(1),
   TRANS_NATURE         CHAR(1),
   BACKGROUND_DATE      VARCHAR2(8),
   RESP_CODE            VARCHAR2(6),
   RESP_MSG             VARCHAR2(192),
   REMARK               VARCHAR2(192)
)
PARTITION BY RANGE (TRANS_DATE)(
	PARTITION PP201401 VALUES LESS THAN ('20140201') TABLESPACE P201401,
	PARTITION PP201402 VALUES LESS THAN ('20140301') TABLESPACE P201402,
	PARTITION PP201403 VALUES LESS THAN ('20140401') TABLESPACE P201403,
	PARTITION PP201404 VALUES LESS THAN ('20140501') TABLESPACE P201404,
	PARTITION PP201405 VALUES LESS THAN ('20140601') TABLESPACE P201405,
	PARTITION PP201406 VALUES LESS THAN ('20140701') TABLESPACE P201406,
	PARTITION PP201407 VALUES LESS THAN ('20140801') TABLESPACE P201407,
	PARTITION PP201408 VALUES LESS THAN ('20140901') TABLESPACE P201408,
	PARTITION PP201409 VALUES LESS THAN ('20141001') TABLESPACE P201409,
	PARTITION PP201410 VALUES LESS THAN ('20141101') TABLESPACE P201410,
	PARTITION PP201411 VALUES LESS THAN ('20141201') TABLESPACE P201411,
	PARTITION PP201412 VALUES LESS THAN ('99999999') TABLESPACE P201412
);

COMMENT ON TABLE "EP_BOEING_TRACE" IS
'BOEING渠道流水';

COMMENT ON COLUMN "EP_BOEING_TRACE".USER_NO IS
'用户ID';

COMMENT ON COLUMN "EP_BOEING_TRACE".ACCT_NO IS
'账号';

COMMENT ON COLUMN "EP_BOEING_TRACE".SYS_SEQ IS
'支付平台流水号';

COMMENT ON COLUMN "EP_BOEING_TRACE".SET_DATE IS
'清算日期';

COMMENT ON COLUMN "EP_BOEING_TRACE".TRANS_ACCT_NO IS
'交易帐号';

COMMENT ON COLUMN "EP_BOEING_TRACE".TRANS_DATE IS
'交易日期';

COMMENT ON COLUMN "EP_BOEING_TRACE".TRANS_TIME IS
'交易时间';

COMMENT ON COLUMN "EP_BOEING_TRACE".TRANS_TYPE IS
'交易类型';

COMMENT ON COLUMN "EP_BOEING_TRACE".SYS_MERCH_NO IS
'商户编号';

COMMENT ON COLUMN "EP_BOEING_TRACE".MERCH_ORDERNO IS
'外部订单号';

COMMENT ON COLUMN "EP_BOEING_TRACE".EXT_ACCT_NO IS
'扩展帐号';

COMMENT ON COLUMN "EP_BOEING_TRACE".TRANS_CURR IS
'交易币种(RMB-156)：RMB、EUR、USD';

COMMENT ON COLUMN "EP_BOEING_TRACE".TRANS_STAT IS
'订单状态：0、成功；1、初始；2、失败； 3、撤销';

COMMENT ON COLUMN "EP_BOEING_TRACE".TRANS_AMT IS
'交易金额';

COMMENT ON COLUMN "EP_BOEING_TRACE".TRANS_FEE IS
'交易手续费';

COMMENT ON COLUMN "EP_BOEING_TRACE".BOEING_SEQ IS
'BOEING流水号';

COMMENT ON COLUMN "EP_BOEING_TRACE".LOG_NUMBER IS
'日志号';

COMMENT ON COLUMN "EP_BOEING_TRACE".SUMMONS_NUM IS
'传票号';

COMMENT ON COLUMN "EP_BOEING_TRACE".DC_FLAG IS
'借贷标志：D、借；C、贷';

COMMENT ON COLUMN "EP_BOEING_TRACE".RB_FLAG IS
'红蓝标志：R、红；B、蓝';

COMMENT ON COLUMN "EP_BOEING_TRACE".TRANS_NATURE IS
'交易性质：1、正常；2、抹账';

COMMENT ON COLUMN "EP_BOEING_TRACE".BACKGROUND_DATE IS
'后台清算日期';

COMMENT ON COLUMN "EP_BOEING_TRACE".RESP_CODE IS
'响应码';

COMMENT ON COLUMN "EP_BOEING_TRACE".RESP_MSG IS
'响应信息';

COMMENT ON COLUMN "EP_BOEING_TRACE".REMARK IS
'备注信息';

ALTER TABLE "EP_BOEING_TRACE"
   ADD CONSTRAINT PK_EP_BOEING_TRACE PRIMARY KEY (SYS_SEQ);

/*==============================================================*/
/* Index: "IDX_EP_BOEING_TRACE1"                                */
/*==============================================================*/
CREATE UNIQUE INDEX "IDX_EP_BOEING_TRACE1" ON "EP_BOEING_TRACE" (
   ACCT_NO ASC,
   SYS_SEQ ASC,
   SET_DATE ASC
);

/*==============================================================*/
/* Index: "IDX_EP_BOEING_TRACE2"                                */
/*==============================================================*/
CREATE UNIQUE INDEX "IDX_EP_BOEING_TRACE2" ON "EP_BOEING_TRACE" (
   USER_NO ASC,
   TRANS_DATE ASC,
   SYS_MERCH_NO ASC,
   MERCH_ORDERNO ASC
);

/*==============================================================*/
/* Table: "EP_DEPOSIT_ACCT_TRACE"                               */
/*==============================================================*/
CREATE TABLE "EP_DEPOSIT_ACCT_TRACE"  (
   ID                   VARCHAR2(32)                    NOT NULL,
   ACCT_NO              VARCHAR2(32),
   TRANS_DATE           VARCHAR2(8),
   TRANS_TIME           VARCHAR2(6),
   TRANS_TYPE           VARCHAR2(6),
   SYS_SEQ              VARCHAR2(32),
   SET_DATE             VARCHAR2(8),
   DC_FLAG              CHAR(1),
   TRANS_CURR           VARCHAR2(3),
   TRANS_AMT            NUMBER(25,2),
   MERCH_NO             VARCHAR2(15),
   MERCH_ORDERNO        VARCHAR2(32),
   IN_ACCT_NO           VARCHAR2(32),
   AB_FLAG              CHAR(1),
   ORIGINAL_NUM         VARCHAR2(32),
   ACCOUNTING_TYPE      CHAR(1),
   PLAFORM_ACCT         VARCHAR2(32),
   STATUS               CHAR(1),
   REMARK               VARCHAR2(200),
   FEE_AMT              NUMBER(25,2)
)
PARTITION BY RANGE (TRANS_DATE)(
	PARTITION PP201401 VALUES LESS THAN ('20140201') TABLESPACE P201401,
	PARTITION PP201402 VALUES LESS THAN ('20140301') TABLESPACE P201402,
	PARTITION PP201403 VALUES LESS THAN ('20140401') TABLESPACE P201403,
	PARTITION PP201404 VALUES LESS THAN ('20140501') TABLESPACE P201404,
	PARTITION PP201405 VALUES LESS THAN ('20140601') TABLESPACE P201405,
	PARTITION PP201406 VALUES LESS THAN ('20140701') TABLESPACE P201406,
	PARTITION PP201407 VALUES LESS THAN ('20140801') TABLESPACE P201407,
	PARTITION PP201408 VALUES LESS THAN ('20140901') TABLESPACE P201408,
	PARTITION PP201409 VALUES LESS THAN ('20141001') TABLESPACE P201409,
	PARTITION PP201410 VALUES LESS THAN ('20141101') TABLESPACE P201410,
	PARTITION PP201411 VALUES LESS THAN ('20141201') TABLESPACE P201411,
	PARTITION PP201412 VALUES LESS THAN ('99999999') TABLESPACE P201412
);

COMMENT ON TABLE "EP_DEPOSIT_ACCT_TRACE" IS
'沉淀账户流水表';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".ID IS
'ID';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".ACCT_NO IS
'账号';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".TRANS_DATE IS
'交易日期';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".TRANS_TIME IS
'交易时间';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".TRANS_TYPE IS
'交易类型';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".SYS_SEQ IS
'支付平台流水号';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".SET_DATE IS
'清算日期';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".DC_FLAG IS
'借贷标志：D、借；C、贷';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".TRANS_CURR IS
'交易币种';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".TRANS_AMT IS
'交易金额';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".MERCH_NO IS
'商户号';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".MERCH_ORDERNO IS
'商户订单号';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".IN_ACCT_NO IS
'贷方帐号';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".AB_FLAG IS
'AB标志：A或者B';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".ORIGINAL_NUM IS
'原日志号';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".ACCOUNTING_TYPE IS
'交易性质：1、正常；2、抹账；3、被抹';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".PLAFORM_ACCT IS
'平台账号';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".STATUS IS
'交易状态：0、成功；1、初始；2、失败； 3、撤销';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".REMARK IS
'备注';

COMMENT ON COLUMN "EP_DEPOSIT_ACCT_TRACE".FEE_AMT IS
'手续费金额';

ALTER TABLE "EP_DEPOSIT_ACCT_TRACE"
   ADD CONSTRAINT PK_EP_DEPOSIT_ACCT_TRACE PRIMARY KEY (ID);

/*==============================================================*/
/* Index: "IDX_EP_DEPOSIT_ACCT_TRACE1"                          */
/*==============================================================*/
CREATE INDEX "IDX_EP_DEPOSIT_ACCT_TRACE1" ON "EP_DEPOSIT_ACCT_TRACE" (
   ACCT_NO ASC,
   SYS_SEQ ASC,
   SET_DATE ASC
);

/*==============================================================*/
/* Index: "IDX_EP_DEPOSIT_ACCT_TRACE2"                          */
/*==============================================================*/
CREATE INDEX "IDX_EP_DEPOSIT_ACCT_TRACE2" ON "EP_DEPOSIT_ACCT_TRACE" (
   ID ASC
);

/*==============================================================*/
/* Table: "EP_INTS_TRACE"                                       */
/*==============================================================*/
CREATE TABLE "EP_INTS_TRACE"  (
   USER_NO              VARCHAR2(128),
   ACCT_NO              VARCHAR2(32),
   SYS_SEQ              VARCHAR2(32)                    NOT NULL,
   SET_DATE             VARCHAR2(8),
   TRANS_ACCT_NO        VARCHAR2(32),
   TRANS_DATE           VARCHAR2(8),
   TRANS_TIME           VARCHAR2(6),
   TRANS_TYPE           VARCHAR2(6),
   SYS_MERCH_NO         VARCHAR2(15),
   MERCH_ORDERNO        VARCHAR2(32),
   EXT_ACCT_NO          VARCHAR2(32),
   TRANS_CURR           VARCHAR2(3),
   TRANS_STAT           CHAR(1),
   TRANS_AMT            NUMBER(25,2),
   LOG_NUMBER           VARCHAR2(32),
   SUMMONS_NUM          VARCHAR2(32),
   DC_FLAG              CHAR(1),
   RB_FLAG              CHAR(1),
   TRANS_NATURE         CHAR(1),
   BACKGROUND_DATE      VARCHAR2(8),
   ACCOUNTING_ENTRY     VARCHAR2(3000),
   ABIS_RESP_CODE       VARCHAR2(8),
   TRADE_SEQ            VARCHAR2(8),
   ENTRUST_DATE         VARCHAR2(8),
   REMIT_BANK_NO        VARCHAR2(16),
   TRANS_FEE            NUMBER(25,2),
   INTS_SEQ             VARCHAR2(32),
   RESP_CODE            VARCHAR2(6),
   RESP_MSG             VARCHAR2(192),
   REMARK               VARCHAR2(192)
)
PARTITION BY RANGE (TRANS_DATE)(
	PARTITION PP201401 VALUES LESS THAN ('20140201') TABLESPACE P201401,
	PARTITION PP201402 VALUES LESS THAN ('20140301') TABLESPACE P201402,
	PARTITION PP201403 VALUES LESS THAN ('20140401') TABLESPACE P201403,
	PARTITION PP201404 VALUES LESS THAN ('20140501') TABLESPACE P201404,
	PARTITION PP201405 VALUES LESS THAN ('20140601') TABLESPACE P201405,
	PARTITION PP201406 VALUES LESS THAN ('20140701') TABLESPACE P201406,
	PARTITION PP201407 VALUES LESS THAN ('20140801') TABLESPACE P201407,
	PARTITION PP201408 VALUES LESS THAN ('20140901') TABLESPACE P201408,
	PARTITION PP201409 VALUES LESS THAN ('20141001') TABLESPACE P201409,
	PARTITION PP201410 VALUES LESS THAN ('20141101') TABLESPACE P201410,
	PARTITION PP201411 VALUES LESS THAN ('20141201') TABLESPACE P201411,
	PARTITION PP201412 VALUES LESS THAN ('99999999') TABLESPACE P201412
);

COMMENT ON TABLE "EP_INTS_TRACE" IS
'INTS渠道流水（一体化）';

COMMENT ON COLUMN "EP_INTS_TRACE".USER_NO IS
'用户ID';

COMMENT ON COLUMN "EP_INTS_TRACE".ACCT_NO IS
'账号';

COMMENT ON COLUMN "EP_INTS_TRACE".SYS_SEQ IS
'支付平台流水号';

COMMENT ON COLUMN "EP_INTS_TRACE".SET_DATE IS
'清算日期';

COMMENT ON COLUMN "EP_INTS_TRACE".TRANS_ACCT_NO IS
'交易帐号';

COMMENT ON COLUMN "EP_INTS_TRACE".TRANS_DATE IS
'交易日期';

COMMENT ON COLUMN "EP_INTS_TRACE".TRANS_TIME IS
'交易时间';

COMMENT ON COLUMN "EP_INTS_TRACE".TRANS_TYPE IS
'交易类型';

COMMENT ON COLUMN "EP_INTS_TRACE".SYS_MERCH_NO IS
'商户编号';

COMMENT ON COLUMN "EP_INTS_TRACE".MERCH_ORDERNO IS
'外部订单号';

COMMENT ON COLUMN "EP_INTS_TRACE".EXT_ACCT_NO IS
'扩展帐号';

COMMENT ON COLUMN "EP_INTS_TRACE".TRANS_CURR IS
'交易币种(RMB-156)：RMB、EUR、USD';

COMMENT ON COLUMN "EP_INTS_TRACE".TRANS_STAT IS
'订单状态：0、成功；1、初始；2、失败； 3、撤销';

COMMENT ON COLUMN "EP_INTS_TRACE".TRANS_AMT IS
'交易金额';

COMMENT ON COLUMN "EP_INTS_TRACE".LOG_NUMBER IS
'日志号';

COMMENT ON COLUMN "EP_INTS_TRACE".SUMMONS_NUM IS
'传票号';

COMMENT ON COLUMN "EP_INTS_TRACE".DC_FLAG IS
'借贷标志：D、借；C、贷';

COMMENT ON COLUMN "EP_INTS_TRACE".RB_FLAG IS
'红蓝标志：R、红；B、蓝';

COMMENT ON COLUMN "EP_INTS_TRACE".TRANS_NATURE IS
'交易性质：1、正常；2、抹账';

COMMENT ON COLUMN "EP_INTS_TRACE".BACKGROUND_DATE IS
'后台清算日期';

COMMENT ON COLUMN "EP_INTS_TRACE".ACCOUNTING_ENTRY IS
'会计分录';

COMMENT ON COLUMN "EP_INTS_TRACE".ABIS_RESP_CODE IS
'Abis应答码';

COMMENT ON COLUMN "EP_INTS_TRACE".TRADE_SEQ IS
'支付交易序号';

COMMENT ON COLUMN "EP_INTS_TRACE".ENTRUST_DATE IS
'委托日期';

COMMENT ON COLUMN "EP_INTS_TRACE".REMIT_BANK_NO IS
'汇出行行号';

COMMENT ON COLUMN "EP_INTS_TRACE".TRANS_FEE IS
'交易手续费';

COMMENT ON COLUMN "EP_INTS_TRACE".INTS_SEQ IS
'INTS流水号';

COMMENT ON COLUMN "EP_INTS_TRACE".RESP_CODE IS
'响应码';

COMMENT ON COLUMN "EP_INTS_TRACE".RESP_MSG IS
'响应信息';

COMMENT ON COLUMN "EP_INTS_TRACE".REMARK IS
'备注信息';

ALTER TABLE "EP_INTS_TRACE"
   ADD CONSTRAINT PK_EP_INTS_TRACE PRIMARY KEY (SYS_SEQ);

/*==============================================================*/
/* Index: "IDX_EP_INTS _TRACE1"                                 */
/*==============================================================*/
CREATE INDEX "IDX_EP_INTS _TRACE1" ON "EP_INTS_TRACE" (
   ACCT_NO ASC,
   SYS_SEQ ASC,
   SET_DATE ASC
);

/*==============================================================*/
/* Index: "IDX_EP_INTS_TRACE2"                                  */
/*==============================================================*/
CREATE INDEX "IDX_EP_INTS_TRACE2" ON "EP_INTS_TRACE" (
   USER_NO ASC,
   TRANS_DATE ASC,
   MERCH_ORDERNO ASC,
   SYS_MERCH_NO ASC
);

/*==============================================================*/
/* Table: "EP_MARKET_TRACE"                                     */
/*==============================================================*/
CREATE TABLE "EP_MARKET_TRACE"  (
   USER_NO              VARCHAR2(128),
   ACCT_NO              VARCHAR2(32),
   SYS_SEQ              VARCHAR2(32)                    NOT NULL,
   SET_DATE             VARCHAR2(8),
   TRANS_ACCT_NO        VARCHAR2(32),
   TRANS_DATE           VARCHAR2(8),
   TRANS_TIME           VARCHAR2(6),
   TRANS_TYPE           VARCHAR2(6),
   SYS_MERCH_NO         VARCHAR2(15),
   MERCH_ORDERNO        VARCHAR2(32),
   EXT_ACCT_NO          VARCHAR2(32),
   TRANS_CURR           VARCHAR2(3),
   TRANS_STAT           CHAR(1),
   TRANS_AMT            NUMBER(25,2),
   TRANS_FEE            NUMBER(25,2),
   MARKET_SEQ           VARCHAR2(32),
   LOG_NUMBER           VARCHAR2(32),
   SUMMONS_NUM          VARCHAR2(32),
   DC_FLAG              CHAR(1),
   RB_FLAG              CHAR(1),
   TRANS_NATURE         CHAR(1),
   BACKGROUND_DATE      VARCHAR2(8),
   RESP_CODE            VARCHAR2(6),
   RESP_MSG             VARCHAR2(192),
   REMARK               VARCHAR2(192)
)
PARTITION BY RANGE (TRANS_DATE)(
	PARTITION PP201401 VALUES LESS THAN ('20140201') TABLESPACE P201401,
	PARTITION PP201402 VALUES LESS THAN ('20140301') TABLESPACE P201402,
	PARTITION PP201403 VALUES LESS THAN ('20140401') TABLESPACE P201403,
	PARTITION PP201404 VALUES LESS THAN ('20140501') TABLESPACE P201404,
	PARTITION PP201405 VALUES LESS THAN ('20140601') TABLESPACE P201405,
	PARTITION PP201406 VALUES LESS THAN ('20140701') TABLESPACE P201406,
	PARTITION PP201407 VALUES LESS THAN ('20140801') TABLESPACE P201407,
	PARTITION PP201408 VALUES LESS THAN ('20140901') TABLESPACE P201408,
	PARTITION PP201409 VALUES LESS THAN ('20141001') TABLESPACE P201409,
	PARTITION PP201410 VALUES LESS THAN ('20141101') TABLESPACE P201410,
	PARTITION PP201411 VALUES LESS THAN ('20141201') TABLESPACE P201411,
	PARTITION PP201412 VALUES LESS THAN ('99999999') TABLESPACE P201412
);

COMMENT ON TABLE "EP_MARKET_TRACE" IS
'交易市场渠道流水';

COMMENT ON COLUMN "EP_MARKET_TRACE".USER_NO IS
'用户ID';

COMMENT ON COLUMN "EP_MARKET_TRACE".ACCT_NO IS
'账号';

COMMENT ON COLUMN "EP_MARKET_TRACE".SYS_SEQ IS
'支付平台流水号';

COMMENT ON COLUMN "EP_MARKET_TRACE".SET_DATE IS
'清算日期';

COMMENT ON COLUMN "EP_MARKET_TRACE".TRANS_ACCT_NO IS
'交易帐号';

COMMENT ON COLUMN "EP_MARKET_TRACE".TRANS_DATE IS
'交易日期';

COMMENT ON COLUMN "EP_MARKET_TRACE".TRANS_TIME IS
'交易时间';

COMMENT ON COLUMN "EP_MARKET_TRACE".TRANS_TYPE IS
'交易类型';

COMMENT ON COLUMN "EP_MARKET_TRACE".SYS_MERCH_NO IS
'商户编号';

COMMENT ON COLUMN "EP_MARKET_TRACE".MERCH_ORDERNO IS
'外部订单号';

COMMENT ON COLUMN "EP_MARKET_TRACE".EXT_ACCT_NO IS
'扩展帐号';

COMMENT ON COLUMN "EP_MARKET_TRACE".TRANS_CURR IS
'交易币种(RMB-156)：RMB、EUR、USD';

COMMENT ON COLUMN "EP_MARKET_TRACE".TRANS_STAT IS
'订单状态：0、成功；1、初始；2、失败； 3、撤销';

COMMENT ON COLUMN "EP_MARKET_TRACE".TRANS_AMT IS
'交易金额';

COMMENT ON COLUMN "EP_MARKET_TRACE".TRANS_FEE IS
'交易手续费';

COMMENT ON COLUMN "EP_MARKET_TRACE".MARKET_SEQ IS
'INTS流水号';

COMMENT ON COLUMN "EP_MARKET_TRACE".LOG_NUMBER IS
'日志号';

COMMENT ON COLUMN "EP_MARKET_TRACE".SUMMONS_NUM IS
'传票号';

COMMENT ON COLUMN "EP_MARKET_TRACE".DC_FLAG IS
'借贷标志：D、借；C、贷';

COMMENT ON COLUMN "EP_MARKET_TRACE".RB_FLAG IS
'红蓝标志：R、红；B、蓝';

COMMENT ON COLUMN "EP_MARKET_TRACE".TRANS_NATURE IS
'交易性质：1、正常；2、抹账';

COMMENT ON COLUMN "EP_MARKET_TRACE".BACKGROUND_DATE IS
'后台清算日期';

COMMENT ON COLUMN "EP_MARKET_TRACE".RESP_CODE IS
'响应码';

COMMENT ON COLUMN "EP_MARKET_TRACE".RESP_MSG IS
'响应信息';

COMMENT ON COLUMN "EP_MARKET_TRACE".REMARK IS
'备注信息';

ALTER TABLE "EP_MARKET_TRACE"
   ADD CONSTRAINT PK_EP_MARKET_TRACE PRIMARY KEY (SYS_SEQ);

/*==============================================================*/
/* Index: "IDX_EP_MARKET _TRACE1"                               */
/*==============================================================*/
CREATE UNIQUE INDEX "IDX_EP_MARKET _TRACE1" ON "EP_MARKET_TRACE" (
   ACCT_NO ASC,
   SYS_SEQ ASC,
   SET_DATE ASC
);

/*==============================================================*/
/* Index: "IDX_EP_MARKET_TRACE2"                                */
/*==============================================================*/
CREATE UNIQUE INDEX "IDX_EP_MARKET_TRACE2" ON "EP_MARKET_TRACE" (
   USER_NO ASC,
   TRANS_DATE ASC,
   SYS_MERCH_NO ASC,
   MERCH_ORDERNO ASC
);

/*==============================================================*/
/* Table: "EP_ORDER_TRACE"                                      */
/*==============================================================*/
CREATE TABLE "EP_ORDER_TRACE"  (
   USER_NO              VARCHAR2(32),
   ACCT_NO              VARCHAR2(32),
   SYS_SEQ              VARCHAR2(32)                    NOT NULL,
   SET_DATE             VARCHAR2(8),
   TRANS_DATE           VARCHAR2(8),
   TRANS_TIME           VARCHAR2(6),
   TRANS_TYPE           VARCHAR2(6),
   MERCH_NO             VARCHAR2(15),
   MERCH_ORDERNO        VARCHAR2(32),
   ORG_MERCH_ORDERNO    VARCHAR2(32),
   SUB_MERCH_NO         VARCHAR2(15),
   SUB_MERCH_NAME       VARCHAR2(60),
   MERCH_DT             VARCHAR2(17),
   ORDER_OVER_DT        VARCHAR2(17),
   PAY_OVER_DT          VARCHAR2(17),
   BACK_OVER_DT         VARCHAR2(17),
   TRANS_CURR           VARCHAR2(3),
   ORDER_AMT            NUMBER(25,2),
   ORDER_FEE_AMT        NUMBER(25,2),
   SYS_FEE_AMT          NUMBER(25,2),
   BLANCE_AMT           NUMBER(25,2),
   EBANK_AMT            NUMBER(25,2),
   FASTPAY_AMT          NUMBER(25,2),
   CREDIT_AMT           NUMBER(25,2),
   ICOIN_PAY_AMT        NUMBER(25,2),
   INSTALLMENT          VARCHAR2(5),
   ORDER_STAT           CHAR(1),
   PAY_FLAG             CHAR(32),
   EXT_ACCT_NO          VARCHAR2(32),
   EXT_ACCT_NAME        VARCHAR2(50),
   FRONT_URL            VARCHAR2(384),
   BACK_URL             VARCHAR2(384),
   SHIPPING_ADDR        VARCHAR2(384),
   GOODS_URL            VARCHAR2(384),
   GOODS_NAME           VARCHAR2(200),
   GOODS_INFO           VARCHAR2(200),
   GOODS_TYPE           CHAR(1),
   REMARK               VARCHAR2(192),
   ACCOUNTING_TYPE      CHAR(1),
   RESP_CODE            VARCHAR2(6),
   RESP_MSG             VARCHAR2(192),
   REVERSE1             VARCHAR2(192),
   REVERSE2             VARCHAR2(192)
)
PARTITION BY RANGE (TRANS_DATE)(
	PARTITION PP201401 VALUES LESS THAN ('20140201') TABLESPACE P201401,
	PARTITION PP201402 VALUES LESS THAN ('20140301') TABLESPACE P201402,
	PARTITION PP201403 VALUES LESS THAN ('20140401') TABLESPACE P201403,
	PARTITION PP201404 VALUES LESS THAN ('20140501') TABLESPACE P201404,
	PARTITION PP201405 VALUES LESS THAN ('20140601') TABLESPACE P201405,
	PARTITION PP201406 VALUES LESS THAN ('20140701') TABLESPACE P201406,
	PARTITION PP201407 VALUES LESS THAN ('20140801') TABLESPACE P201407,
	PARTITION PP201408 VALUES LESS THAN ('20140901') TABLESPACE P201408,
	PARTITION PP201409 VALUES LESS THAN ('20141001') TABLESPACE P201409,
	PARTITION PP201410 VALUES LESS THAN ('20141101') TABLESPACE P201410,
	PARTITION PP201411 VALUES LESS THAN ('20141201') TABLESPACE P201411,
	PARTITION PP201412 VALUES LESS THAN ('99999999') TABLESPACE P201412
);

COMMENT ON TABLE "EP_ORDER_TRACE" IS
'订单流水表';

COMMENT ON COLUMN "EP_ORDER_TRACE".USER_NO IS
'用户ID';

COMMENT ON COLUMN "EP_ORDER_TRACE".ACCT_NO IS
'账号';

COMMENT ON COLUMN "EP_ORDER_TRACE".SYS_SEQ IS
'支付平台流水号';

COMMENT ON COLUMN "EP_ORDER_TRACE".SET_DATE IS
'清算日期';

COMMENT ON COLUMN "EP_ORDER_TRACE".TRANS_DATE IS
'交易日期';

COMMENT ON COLUMN "EP_ORDER_TRACE".TRANS_TIME IS
'交易时间';

COMMENT ON COLUMN "EP_ORDER_TRACE".TRANS_TYPE IS
'交易类型';

COMMENT ON COLUMN "EP_ORDER_TRACE".MERCH_NO IS
'平台商户号';

COMMENT ON COLUMN "EP_ORDER_TRACE".MERCH_ORDERNO IS
'商户订单号';

COMMENT ON COLUMN "EP_ORDER_TRACE".SUB_MERCH_NO IS
'子商户代码';

COMMENT ON COLUMN "EP_ORDER_TRACE".SUB_MERCH_NAME IS
'子商户名称';

COMMENT ON COLUMN "EP_ORDER_TRACE".MERCH_DT IS
'订单日期';

COMMENT ON COLUMN "EP_ORDER_TRACE".ORDER_OVER_DT IS
'订单超时时间';

COMMENT ON COLUMN "EP_ORDER_TRACE".PAY_OVER_DT IS
'支付超时时间';

COMMENT ON COLUMN "EP_ORDER_TRACE".BACK_OVER_DT IS
'退单限制时间';

COMMENT ON COLUMN "EP_ORDER_TRACE".TRANS_CURR IS
'交易币种(RMB-156)：RMB、EUR、USD';

COMMENT ON COLUMN "EP_ORDER_TRACE".ORDER_AMT IS
'订单金额';

COMMENT ON COLUMN "EP_ORDER_TRACE".ORDER_FEE_AMT IS
'订单手续费';

COMMENT ON COLUMN "EP_ORDER_TRACE".SYS_FEE_AMT IS
'平台手续费';

COMMENT ON COLUMN "EP_ORDER_TRACE".BLANCE_AMT IS
'余额支付金额';

COMMENT ON COLUMN "EP_ORDER_TRACE".EBANK_AMT IS
'网银支付金额';

COMMENT ON COLUMN "EP_ORDER_TRACE".FASTPAY_AMT IS
'快捷支付金额';

COMMENT ON COLUMN "EP_ORDER_TRACE".CREDIT_AMT IS
'信用卡支付金额';

COMMENT ON COLUMN "EP_ORDER_TRACE".ICOIN_PAY_AMT IS
'农银通宝币支付金额';

COMMENT ON COLUMN "EP_ORDER_TRACE".INSTALLMENT IS
'分期数';

COMMENT ON COLUMN "EP_ORDER_TRACE".ORDER_STAT IS
'订单状态：0 、成功 1、初始 2、失败 3、支付中、4状态未知、5、已退款、6、已撤销；7、农银通币支付成功；8、余额支付成功';

COMMENT ON COLUMN "EP_ORDER_TRACE".PAY_FLAG IS
'第X位的解释：0、我行账户(0-为我行账户，1-为他行账户）
1、快捷支付
2、网银支付
3、信用卡支付
4、信用卡分期支付
5、 对公账户支付
6、余额支付
7、积分支付
8-31：保留

';

COMMENT ON COLUMN "EP_ORDER_TRACE".EXT_ACCT_NO IS
'扩展帐号';

COMMENT ON COLUMN "EP_ORDER_TRACE".FRONT_URL IS
'前台通知地址';

COMMENT ON COLUMN "EP_ORDER_TRACE".BACK_URL IS
'后台通知地址';

COMMENT ON COLUMN "EP_ORDER_TRACE".SHIPPING_ADDR IS
'收货地址';

COMMENT ON COLUMN "EP_ORDER_TRACE".GOODS_URL IS
'商品URL';

COMMENT ON COLUMN "EP_ORDER_TRACE".GOODS_NAME IS
'商品名称';

COMMENT ON COLUMN "EP_ORDER_TRACE".GOODS_INFO IS
'商品信息';

COMMENT ON COLUMN "EP_ORDER_TRACE".GOODS_TYPE IS
'1、非实体商品；2、实体商品';

COMMENT ON COLUMN "EP_ORDER_TRACE".REMARK IS
'备注信息';

COMMENT ON COLUMN "EP_ORDER_TRACE".ACCOUNTING_TYPE IS
'账务类型：1、正常；2、抹账；3、被抹；4、冲正';

COMMENT ON COLUMN "EP_ORDER_TRACE".RESP_CODE IS
'响应码';

COMMENT ON COLUMN "EP_ORDER_TRACE".RESP_MSG IS
'响应信息';

COMMENT ON COLUMN "EP_ORDER_TRACE".REVERSE1 IS
'保留1';

COMMENT ON COLUMN "EP_ORDER_TRACE".REVERSE2 IS
'保留2';

ALTER TABLE "EP_ORDER_TRACE"
   ADD CONSTRAINT PK_EP_ORDER_TRACE PRIMARY KEY (SYS_SEQ);

/*==============================================================*/
/* Index: "IDX_EP_ORDER_TRACE2"                                 */
/*==============================================================*/
CREATE UNIQUE INDEX "IDX_EP_ORDER_TRACE2" ON "EP_ORDER_TRACE" (
   ACCT_NO ASC,
   SYS_SEQ ASC,
   SET_DATE ASC
);

/*==============================================================*/
/* Index: "IDX_EP_ORDER_TRACE3"                                 */
/*==============================================================*/
CREATE UNIQUE INDEX "IDX_EP_ORDER_TRACE3" ON "EP_ORDER_TRACE" (
   USER_NO ASC,
   TRANS_DATE ASC,
   MERCH_NO ASC,
   MERCH_ORDERNO ASC
);

/*==============================================================*/
/* Index: "IDX_EP_ORDER_TRACE4"                                 */
/*==============================================================*/
CREATE INDEX "IDX_EP_ORDER_TRACE4" ON "EP_ORDER_TRACE" (
   TRANS_TYPE ASC
);

